---
- name: Ajoute le script pour pouvoir mettre les données de production sur cet environnement
  template:
    src: apply-prod
    dest: /srv/scripts/
    mode: u=rwx,g=rx,o=r
    owner: git
    group: users
  become: True
- name: Ajoute l'utilisateur "prod"
  ansible.builtin.user:
    name: prod
    group: users
    home: /srv/backups
  become: True
- name: Donne les droits à la home de l'utilisateur "prod"
  file:
    path: /srv/backups
    owner: git
    group: users
  become: True
# FIXME remove this from dev and preprod
# REMOVE 'prod' user
# Remove transfer_data_to_dev_and_preprod from prod
# Remove transfer_data_to_dev_and_preprod cron from prod
- name: Ajoute le job de restauration du backup de la prod
  ansible.builtin.cron:
    name: "backup"
    minute: "0"
    hour: "6"
    weekday: "0"
    job: "/srv/scripts/apply-prod"
    user: git
  become: True
  when: env == 'dev'