---
- name: Ajoute le script pour pouvoir mettre les données de production sur cet environnement
  template:
    src: apply-prod
    dest: /srv/scripts/
    mode: u=rwx,g=rx,o=r
    owner: git
    group: users
  become: True
- name: Donne les droits du dossier de backup à l'utilisateur "git"
  file:
    path: /srv/backups
    owner: git
    group: users
  become: True
- name: Ajoute le job de restauration du backup de la prod
  ansible.builtin.cron:
    name: "backup"
    minute: "0"
    hour: "6"
    weekday: "0"
    job: "/srv/scripts/apply-prod"
    user: git
  become: True
  when: env == 'dev'