FROM python:3.10.13

RUN pip install --upgrade pip && \
    pip install openfisca-france-fiscalite-miniere==5.2.0


ENTRYPOINT ["openfisca", "serve", "--country-package", "openfisca_france_fiscalite_miniere", "--bind", "0.0.0.0"]
