FROM python:3.7

RUN pip install --upgrade pip && \
    pip install openfisca-france-fiscalite-miniere==3.0.2 && \
    # en attente de https://github.com/openfisca/openfisca-core/pull/1130
    pip install --upgrade flask


ENTRYPOINT ["openfisca", "serve", "--country-package", "openfisca_france_fiscalite_miniere", "--bind", "0.0.0.0"]