version: '3'

services:
  app:
    container_name: camino_api_app
    build: .
    depends_on:
      - db
    environment:
      VIRTUAL_HOST: ${URL}
      VIRTUAL_PORT: ${NODE_PORT}
      PGHOST: db
    expose:
      - ${NODE_PORT}
    networks:
      - default
      - nginx-proxy
    volumes:
      - files:/app/files
      - ./.env:/app/.env

  db:
    container_name: camino_api_db
    image: postgres:12-alpine
    environment:
      PGUSER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    expose:
      - ${PGPORT}
    networks:
      - default
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: {}
  files:

networks:
  nginx-proxy:
    external: true
