version: '3'

services:
  openfisca:
    build:
      context: .
      dockerfile: Dockerfile.openfisca
    restart: unless-stopped
    ports:
      - 8000:8000
  api:
    container_name: camino_api_app
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - db
      - openfisca
    environment:
      PGHOST: db
    expose:
      - ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./.env:/.env
  db:
    container_name: camino_api_db
    image: postgis/postgis:12-3.2
    environment:
      PGUSER: ${PGUSER}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    expose:
      - ${PGPORT}
    ports:
      - ${PGPORT}:${PGPORT}
  ui:
    container_name: camino_ui_app
    build:
      context: .
      dockerfile: Dockerfile.ui
      args:
        GIT_SHA: unused
    environment:
      UI_PORT: ${UI_PORT}
      API_URL: ${API_URL}
      API_MATOMO_URL: ${API_MATOMO_URL}
    ports:
      - ${UI_PORT}:${UI_PORT}

