version: '3'

services:
  openfisca:
    image: caminofr/camino-openfisca:${CAMINO_TAG}
    restart: unless-stopped
  api:
    container_name: camino_api_app
    image: caminofr/camino-api:${CAMINO_TAG}
    depends_on:
      - db
      - openfisca
    environment:
      CAMINO_STAGE: ${ENV}
      APPLICATION_VERSION: ${CAMINO_TAG}
      VIRTUAL_HOST: ${API_HOST}
      VIRTUAL_PORT: ${API_PORT}
      LETSENCRYPT_HOST: ${API_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      PGHOST: db
    expose:
      - ${API_PORT}
    volumes:
      - ./files:/packages/api/files
      - ./.env:/.env
    networks:
      - default
      - nginx-proxy
    restart: unless-stopped
  db:
    container_name: camino_api_db
    image: postgis/postgis:12-3.2
    environment:
      PGUSER: ${PGUSER}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    expose:
      - ${PGPORT}
    networks:
      - default
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    restart: unless-stopped
  docs:
    container_name: camino_api_docs
    image: caminofr/camino-api-docs:${CAMINO_TAG}
    environment:
      VIRTUAL_HOST: ${DOC_HOST}
      VIRTUAL_PORT: ${DOC_PORT}
      LETSENCRYPT_HOST: ${DOC_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    expose:
      - ${DOC_PORT}
    networks:
      - default
      - nginx-proxy
    restart: unless-stopped
  ui:
    container_name: camino_ui_app
    image: caminofr/camino-ui:${CAMINO_TAG}
    environment:
      VIRTUAL_HOST: ${UI_HOST}
      VIRTUAL_PORT: ${UI_PORT}
      LETSENCRYPT_HOST: ${UI_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      UI_PORT: ${UI_PORT}
      API_URL: http://api:${API_PORT}
      API_MATOMO_URL: ${API_MATOMO_URL}
    expose:
      - ${UI_PORT}
    networks:
      - default
      - nginx-proxy
    restart: unless-stopped
  storybook:
    container_name: camino_ui_storybook
    image: caminofr/camino-ui-storybook:${CAMINO_TAG}
    environment:
      VIRTUAL_HOST: ${STORYBOOK_HOST}
      VIRTUAL_PORT: ${STORYBOOK_PORT}
      LETSENCRYPT_HOST: ${STORYBOOK_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    expose:
      - ${STORYBOOK_PORT}
    networks:
      - default
      - nginx-proxy
    restart: unless-stopped

networks:
  nginx-proxy:
    external: true

