#https://github.com/fabriziocucci/vuejs.org/blob/7f9aa12833c085b97a826df3ba240f7d9e069e1b/src/v2/cookbook/dockerize-vuejs-app.md

FROM node:20.3-alpine as build-stage
LABEL maintainer=francois.romain@beta.gouv.fr
ARG GIT_SHA
ENV GIT_SHA=${GIT_SHA}
WORKDIR /app
RUN apk add make
COPY package*.json /app/
COPY packages/common/package.json /app/packages/common/package.json
COPY packages/ui/package.json /app/packages/ui/package.json
COPY Makefile /app/Makefile
RUN CI=true make install

COPY ./ /app/
RUN make build/ui

FROM nginx:1.23.2
ADD ui_nginx.conf /etc/nginx/templates/default.conf.template
COPY --from=build-stage /app/packages/ui/dist /usr/share/nginx/html