version: '3'

services:
  app:
    container_name: camino_api_app
    image: node:alpine
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - db
    environment:
      PGHOST: db
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    command: npm run dev

  db:
    container_name: camino_api_db
    image: postgres:12-alpine
    environment:
      PGUSER: ${PGUSER}
    expose:
      - ${PGPORT}
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: {}
