version: '3'

services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      VIRTUAL_HOST: ${URL}
      VIRTUAL_PORT: ${NODE_PORT}
      LETSENCRYPT_HOST: ${URL}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      PGHOST: postgres
    expose:
      - ${NODE_PORT}
    volumes:
      - files:/app/files
      - ./.env:/app/.env

  postgres:
    image: postgres:12-alpine
    environment:
      PGUSER: ${PGUSER}
    expose:
      - ${PGPORT}
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: {}
  files:

networks:
  default:
    external:
      name: nginx-proxy
