version: '3'

services:
  app:
    image: node:alpine
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - postgres
    environment:
      PGHOST: postgres
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    command: npm run dev

  postgres:
    image: postgres:12-alpine
    environment:
      PGUSER: ${PGUSER}
    expose:
      - ${PGPORT}
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: {}
