const fs = require('fs')
const path = require('path')
const readline = require('readline')
const iconExtractor = /id="icon-([^ ]*)"/

const fileName = 'iconSprite.tsx'
function generateTypes(): void {
  function getIconSpritePath(): string {
    return path.join(__dirname, '..', 'src', 'components', '_ui', fileName)
  }

  function getIconSpritePathTypes(): string {
    return path.join(__dirname, '..', 'src', 'components', '_ui', 'iconSpriteType.ts')
  }

  const rl = readline.createInterface({
    input: fs.createReadStream(getIconSpritePath()),
    output: process.stdout,
    terminal: false,
  })

  const icons: string[] = []
  rl.on('line', line => {
    const captured = line.match(iconExtractor)
    if (captured != null) {
      icons.push(captured[1])
    }
  })
  rl.on('close', () => {
    fs.writeFileSync(
      getIconSpritePathTypes(),
      `// Generated by 'scripts/generateIconTypes.ts', DO NOT MODIFY MANUALLY
// add new icons in the ${fileName} and run 'npm run generate-icon-types -w packages/ui', or commit and husky will do it
// prettier-ignore
export const icons=${JSON.stringify(icons.sort())} as const
export type Icon = typeof icons[number]
    `
    )
  })
}

function generateDsfrIconTypes(): void {
  function getIconPath(): string {
    return path.join(__dirname, '..', 'src', 'styles', 'dsfr', 'icons')
  }

  function getIconSpritePathTypes(): string {
    return path.join(__dirname, '..', 'src', 'components', '_ui', 'dsfrIconSpriteType.ts')
  }

  const iconPath = getIconPath()
  const folders = fs.readdirSync(getIconPath())

  const iconNames = folders.flatMap(folder => {
    const iconFiles = fs.readdirSync(path.join(iconPath, folder))
    return (
      iconFiles
        .map(fileName => fileName.replace(/\.[^/.]+$/, ''))
        // TODO 2023-07-03 les noms de fichiers des icones du dsfr ne sont pas consistants avec les noms des classes........
        .map(fileName => fileName.replace('fr--', ''))
    )
  })

  fs.writeFileSync(
    getIconSpritePathTypes(),
    `// Generated by 'scripts/generateIconTypes.ts', DO NOT MODIFY MANUALLY
// add new icons in the ${fileName} and run 'npm run generate-icon-types -w packages/ui', or commit and husky will do it
// prettier-ignore
const icons=${JSON.stringify(iconNames.sort())} as const
export type DsfrIcon = \`fr-icon-\${typeof icons[number]}\`
    `
  )
}

generateTypes()
generateDsfrIconTypes()
