---
- name: Upgrade machine
  ansible.builtin.apt:
    upgrade: safe
    update_cache: yes
  become: True
- name: Install rsync
  ansible.builtin.apt:
    name: rsync
    state: present
  become: True
- name: Install docker
  ansible.builtin.apt:
    name: docker-ce
    state: latest
  become: True
- name: Install docker client
  ansible.builtin.apt:
    name: docker-ce-cli
    state: latest
  become: True