---
- name: Upgrade machine
  ansible.builtin.apt:
    upgrade: safe
    update_cache: yes
  become: True
- name: Install rsync
  ansible.builtin.apt:
    name: rsync
    state: present
  become: True
- name: Install docker
  ansible.builtin.apt:
    name: docker-ce
    state: latest
  become: True
- name: Install docker client
  ansible.builtin.apt:
    name: docker-ce-cli
    state: latest
  become: True
- name: Install docker compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-linux-x86_64
    checksum: sha256:1178848502b0771b96895febeb4b1736acd5019c4ed71a8efbabf6915185fe8a
    dest: /usr/local/bin/docker-compose
    mode: u=rwx,g=rx,o=rx
    owner: git
    group: users
  become: True