---
- hosts: servers
  vars:
    # L'UID doit être le même que dans le Dockerfile.api
    camino_user_uid: 1002
    # Le GID doit être le même que dans le Dockerfile.api
    camino_user_gid: 1002
  roles:
    - role: swap
      when: ansible_swaptotal_mb < 1
    - role: user
    - role: init
    - role: nginx
    - role: camino
    - role: prod
      when: env == 'prod'
  tasks:
    - name: 2024-09-09 Remove old nginx storybook redirect (remove this once run through the prod)
      ansible.builtin.file:
        path: /srv/www/nginx-proxy/redirect.conf
        state: absent
      become: True
