---
- hosts: servers
  tasks:
    - name: Install rsync
      ansible.builtin.apt:
        name: rsync
        state: present
      become: True
  roles:
    - role: user
    - role: nginx
    - role: camino
    - role: devAndPreprod
      when: env != 'prod'
    - role: prod
      when: env == 'prod'

