---
- hosts: servers
  vars:
    # L'UID doit être le même que dans le Dockerfile.api
    camino_user_uid: 1002
    # Le GID doit être le même que dans le Dockerfile.api
    camino_user_gid: 1002
  roles:
    - role: swap
      when: ansible_swaptotal_mb < 1
    - role: user
    - role: init
    - role: nginx
    - role: camino
    - role: prod
      when: env == 'prod'
  tasks:
    - name: Remove old docker-compose (remove this once run through the prod)
      ansible.builtin.file:
        path: /usr/local/bin/docker-compose
        state: absent
      become: True
    - name: 2024-05-29 -> Remove old keycloak-franceconnect (remove this once run through the prod)
      ansible.builtin.file:
        path: /srv/www/camino/keycloak-bcrypt-1.6.0.jar
        state: absent
      become: True
