---
- hosts: servers
  tasks:
    - name: Install rsync
      ansible.builtin.apt:
        name: rsync
        state: present
      become: True
    - file:
        path: /srv/www/camino/files
        group: users
        mode: u=rwx,g=rwx,o=r
      become: True
  roles:
    - role: nginx
    - role: devAndPreprod
      when: not prod
    - role: prod
      when: prod

