---
- hosts: servers
  vars:
    # L'UID doit être le même que dans le Dockerfile.api
    git_user_uid: 1002
  roles:
    - role: swap
      when: ansible_swaptotal_mb < 1
    - role: user
    - role: init
    - role: nginx
    - role: camino
    - role: prod
      when: env == 'prod'

