import { CaminoDate, toCaminoDate } from '../date.js'
import { Definition } from '../definition.js'

export const ETAPES_TYPES = {
  avisDeDirectionRegionaleDesAffairesCulturelles: 'aac',
  avisDeLaDirectionDalimentationDeLagricultureEtDeLaForet: 'aaf',
  abrogationDeLaDecision: 'abd',
  avisDGTMServiceMilieuxNaturelsBiodiversiteSitesEtPaysages_MNBST_: 'abs',
  avisDeLaCommissionDesAutorisationsDeRecherchesMinieres_CARM_: 'aca',
  avisDuConseilDepartementalDeLenvironnementEtDesRisquesSanitairesEtTechnologiques_Coderst_: 'acd',
  avisDuConseilGeneralDeLeconomie_CGE_: 'acg',
  avisDuneCollectiviteLocale: 'acl',
  avenantALautorisationDeRechercheMiniere: 'aco',
  avisDeLaDirectionDesEntreprisesDeLaConcurrenceDeLaConsommationDuTravailEtDeLemploi: 'aec',
  avisDunPresidentDEPCI: 'aep',
  avisDeLaDirectionRegionaleDesFinancesPubliques: 'afp',
  avisDeLaGendarmerieNationale: 'agn',
  avisDeLIfremer: 'aim',
  avisDunMaire: 'ama',
  avisDuParcNaturelMarin: 'ami',
  decisionDuJugeAdministratif: 'and',
  avisDeMiseEnConcurrenceAuJOUE: 'ane',
  avisDeMiseEnConcurrenceAuJORF: 'anf',
  avisDeLOfficeNationalDesForets: 'aof',
  avisDeLInstitutNationalDeLorigineEtDeLaQualite: 'aop',
  avisEtRapportDuDirecteurRegionalChargeDeLenvironnementDeLamenagementEtDuLogement: 'apd',
  avisDuConseilDEtat: 'ape',
  avisDeLetatMajorOrpaillageEtPecheIllicite_EMOPI_: 'api',
  avisDunServiceAdministratifLocal: 'apl',
  avisDeLautoriteMilitaire: 'apm',
  avisDuParcNational: 'apn',
  avisDeLaCommissionDepartementaleDesMines_CDM_: 'apo',
  avisDuPrefet: 'app',
  publicationDeLavisDeDecisionImplicite: 'apu',
  avisDuPrefetMaritime: 'apw',
  avisDeLaReunionInterservice: 'ari',
  avisDeLagenceRegionaleDeSante: 'ars',
  decisionDuProprietaireDuSol: 'asl',
  avisDeLaCaisseGeneraleDeSecuriteSociale: 'ass',
  avisDGTMServiceAmenagementUrbanismeConstructionLogement_AUCL_: 'auc',
  consultationDesAdministrationsCentrales: 'cac',
  consultationCLEDuSAGE: 'ccs',
  concertationInterministerielle: 'cim',
  saisineDuConseilDepartementalDeLenvironnementEtDesRisquesSanitairesEtTechnologiques_Coderst_: 'cod',
  confirmationDeLaccordDuProprietaireDuSol: 'cps',
  classementSansSuite: 'css',
  decisionDeLaMissionAutoriteEnvironnementale_ExamenAuCasParCasDuProjet_: 'dae',
  declaration: 'dec',
  decisionDeLOfficeNationalDesForets: 'def',
  desistementDuDemandeur: 'des',
  decisionDeLadministration: 'dex',
  decisionImplicite: 'dim',
  publicationDeDecisionAuJORF: 'dpu',
  publicationDeDecisionAdministrativeAuJORF: 'dup',
  decisionAdministrative: 'dux',
  expertiseDREALOuDGTMServiceEau: 'ede',
  expertiseDGTMServicePreventionDesRisquesEtIndustriesExtractives_DATE_: 'edm',
  expertiseDeLOfficeNationalDesForets: 'eof',
  clotureDeLenquetePublique: 'epc',
  ouvertureDeLenquetePublique: 'epu',
  expertiseDREALOuDGTMServiceBiodiversite: 'esb',
  initiationDeLaDemarcheDeRetrait: 'ide',
  informationsHistoriquesIncompletes: 'ihi',
  demandeDeComplements_RecevabiliteDeLaDemande_: 'mca',
  demandeDeComplements_RecepisseDeDeclarationLoiSurLeau_: 'mcb',
  demandeDeComplements_DecisionDeLaMissionAutoriteEnvironnementale_ExamenAuCasParCasDuProjet_: 'mcd',
  demandeDeComplements_CompletudeDeLaDemande_: 'mcm',
  demandeDeComplements: 'mco',
  completudeDeLaDemande: 'mcp',
  recevabiliteDeLaDemande: 'mcr',
  demandeDeComplements_SaisineDeLaCARM_: 'mcs',
  depotDeLaDemande: 'mdp',
  avisDeDemandeConcurrente: 'mec',
  enregistrementDeLaDemande: 'men',
  priseEnChargeParLOfficeNationalDesForets: 'meo',
  demande: 'mfr',
  demandeDinformations_AvisDeLOfficeNationalDesForets_: 'mia',
  demandeDinformations_AvisDuDREALDEALOuDGTM_: 'mie',
  demandeDinformations: 'mif',
  demandeDinformations_RecevabiliteDeLaDemande_: 'mim',
  demandeDinformations_ExpertiseDeLOfficeNationalDesForets_: 'mio',
  notificationAuDemandeur_AjournementDeLaCARM_: 'mna',
  notificationAuDemandeur_AvisFavorableDeLaCARM_: 'mnb',
  notificationAuDemandeur_ClassementSansSuite_: 'mnc',
  notificationAuDemandeur_AvisDefavorable_: 'mnd',
  notificationAuDemandeur_InitiationDeLaDemarcheDeRetrait_: 'mni',
  notificationAuDemandeur: 'mno',
  notificationAuDemandeur_SignatureDeLautorisationDeRechercheMiniere_: 'mns',
  notificationAuDemandeur_SignatureDeLavenantALautorisationDeRechercheMiniere_: 'mnv',
  modificationDeLaDemande: 'mod',
  modificationDeLaDemande_DecisionDeLaMissionAutoriteEnvironnementale_ExamenAuCasParCasDuProjet_: 'mom',
  notificationDesCollectivitesLocales: 'ncl',
  noteInterneSignalee: 'nis',
  notificationAuPrefet: 'npp',
  paiementDesFraisDeDossierComplementaires: 'pfc',
  paiementDesFraisDeDossier: 'pfd',
  avisDuParcNaturelRegional: 'pnr',
  clotureDeLaParticipationDuPublic: 'ppc',
  ouvertureDeLaParticipationDuPublic: 'ppu',
  publicationDansUnJournalLocalOuNational: 'pqr',
  receptionDeComplements_RecevabiliteDeLaDemande_: 'rca',
  receptionDeComplements_RecepisseDeDeclarationLoiSurLeau_: 'rcb',
  receptionDeComplements_DecisionDeLaMissionAutoriteEnvironnementale_ExamenAuCasParCasDuProjet__: 'rcd',
  rapportDuConseilGeneralDeLeconomie_CGE_: 'rcg',
  receptionDeComplements_CompletudeDeLaDemande_: 'rcm',
  receptionDeComplements: 'rco',
  receptionDeComplements_SaisineDeLaCARM_: 'rcs',
  recepisseDeDeclarationLoiSurLeau: 'rde',
  receptionDinformation_AvisDeLOfficeNationalDesForets_: 'ria',
  receptionDinformation_AvisDuDREALDEALOuDGTM_: 'rie',
  receptionDinformation: 'rif',
  receptionDinformation_RecevabiliteDeLaDemande_: 'rim',
  receptionDinformation_ExpertiseDeLOfficeNationalDesForets_: 'rio',
  rapportDuConseilDEtat: 'rpe',
  publicationDeDecisionAuRecueilDesActesAdministratifs: 'rpu',
  retraitDeLaDecision: 'rtd',
  saisineDeLautoriteSignataire: 'sas',
  saisineDeLaCommissionDesAutorisationsDeRecherchesMinieres_CARM_: 'sca',
  saisineDuConseilGeneralDeLeconomie_CGE_: 'scg',
  saisineDesCollectivitesLocales: 'scl',
  signatureDeLautorisationDeRechercheMiniere: 'sco',
  saisineDuConseilDEtat: 'spe',
  saisineDeLaCommissionDepartementaleDesMines_CDM_: 'spo',
  saisineDuPrefet: 'spp',
  saisineDesServices: 'ssr',
  validationDuPaiementDesFraisDeDossierComplementaires: 'vfc',
  validationDuPaiementDesFraisDeDossier: 'vfd',
  abandonDeLaDemande: 'wab',
  avisDeDirectionRegionaleDesAffairesCulturellesDRAC: 'wac',
  avisDeLaDirectionDepartementaleDesTerritoiresEtDeLaMerDDT_M_: 'wad',
  avisDeLautoriteEnvironnementale: 'wae',
  avisDesAutresInstances: 'wai',
  avisDunServiceAdministratifLocal_wal: 'wal',
  avisDeLautoriteMilitaire_wam: 'wam',
  arreteDouvertureDesTravauxMiniers: 'wao',
  avisDuPrefetMaritime_wap: 'wap',
  avisDeReception: 'war',
  avisDeLagenceRegionaleDeSanteARS: 'was',
  avisDuConseilDepartementalDeLenvironnementEtDesRisquesSanitairesEtTechnologiques_Coderst__wat: 'wat',
  avisDuDemandeurSurLesPrescriptionsProposees: 'wau',
  clotureDeLenquetePublique_wce: 'wce',
  receptionDeComplements_wco: 'wco',
  donneActeDeLaDeclaration_DOTM_: 'wda',
  demandeDeComplements_AOTMOuDOTM_: 'wdc',
  depotDeLaDemande_wdd: 'wdd',
  demandeDeComplements_DADT_: 'wde',
  decisionDeLadministration_wdm: 'wdm',
  avisDeLaDDT_M_: 'wdt',
  demandeDautorisationDouvertureDeTravauxMiniers_AOTM_: 'wfa',
  declarationDarretDefinitifDeTravaux_DADT_: 'wfd',
  declarationDouvertureDeTravauxMiniers_DOTM_: 'wfo',
  demandeDautorisationDouvertureDeTravauxMiniers_DAOTM_: 'wfr',
  memoireEnReponseDeLexploitant_ParRapportALavisDeLAE_: 'wmm',
  memoireEnReponseDeLexploitant: 'wmr',
  memoireDeFinDeTravaux: 'wmt',
  ouvertureDeLenquetePublique_woe: 'woe',
  publicationDeDecisionAuRecueilDesActesAdministratifs_wpa: 'wpa',
  porterAConnaissance: 'wpb',
  arreteDePrescriptionsComplementaires: 'wpc',
  arreteDeSecondDonnerActe: 'wpo',
  arretePrefectoralDePremierDonnerActe_DADT_: 'wpp',
  arretePrefectoralDeSursisAStatuer: 'wps',
  receptionDeComplements_wrc: 'wrc',
  rapportDeLaDreal: 'wrd',
  recevabilite: 'wre',
  avisEtRapportDuDirecteurRegionalChargeDeLenvironnementDeLamenagementEtDuLogement_wrl: 'wrl',
  recolement: 'wrt',
  saisineDeLautoriteEnvironnementale: 'wse',
  saisineDesServicesDeLEtat: 'wss',
  transmissionDuProjetDePrescriptionsAuDemandeur: 'wtp',
} as const

export type EtapeTypeId = (typeof ETAPES_TYPES)[keyof typeof ETAPES_TYPES]
export type EtapeTypeKey = keyof typeof ETAPES_TYPES

export const etapesTypesIds = Object.values(ETAPES_TYPES)
export type EtapeType<T = EtapeTypeId> = Omit<Definition<T>, 'ordre'> & { unique: boolean; fondamentale: boolean; dateFin: CaminoDate | null }
export const EtapesTypes: { [key in EtapeTypeId]: EtapeType<key> } = {
  aac: {
    id: 'aac',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'avis de direction régionale des affaires culturelles',
    description: 'Avis sur la situation archéologique du site en question.',
  },
  aaf: { id: 'aaf', dateFin: null, fondamentale: false, unique: false, nom: "avis de la direction d'alimentation de l'agriculture et de la forêt", description: 'Avis pour un titre minier.' },
  abd: { id: 'abd', dateFin: null, fondamentale: true, unique: false, nom: 'abrogation de la décision', description: 'Suppression de l’acte administratif pour l’avenir.' },
  abs: {
    id: 'abs',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'avis DGTM service milieux naturels, biodiversité, sites et paysages (MNBST)',
    description: "Avis du MNBST sur la notice d’impact pour les titres miniers et les autorisations d'exploitation.",
  },
  aca: { id: 'aca', dateFin: null, fondamentale: true, unique: true, nom: 'avis de la commission des autorisations de recherches minières (CARM)', description: '' },
  acd: { id: 'acd', dateFin: null, fondamentale: false, unique: false, nom: "avis du conseil départemental de l'environnement et des risques sanitaires et technologiques (Coderst)", description: '' },
  acg: {
    id: 'acg',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: "avis du conseil général de l'économie (CGE)",
    description: "Le conseil général de l'économie donne un avis sur la demande et sur son instruction au ministre chargé des mines. Cet avis n'est pas conforme.",
  },
  acl: {
    id: 'acl',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: "avis d'une collectivité locale",
    description: "Avis de la collectivité locale dans le cadre de l’instruction d’un titre ou d'une demande relative à la police des mines.",
  },
  aco: {
    id: 'aco',
    dateFin: null,
    fondamentale: true,
    unique: false,
    nom: 'avenant à l’autorisation de recherche minière',
    description: 'Document (courrier) validant une demande de renouvellement et actant la prolongation de la durée de l’autorisation.',
  },
  aec: {
    id: 'aec',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: "avis de la direction des entreprises, de la concurrence, de la consommation, du travail et de l'emploi",
    description: 'Avis facultatif sur la situation économique de l’entreprise.',
  },
  aep: {
    id: 'aep',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: "avis d'un président d'EPCI",
    description: "Avis du président d’EPCI dans le cadre de l’instruction d’un titre ou d'une demande relative à la police des mines.",
  },
  afp: {
    id: 'afp',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'avis de la direction régionale des finances publiques',
    description: 'Avis délivré sur la régularité fiscale de l’entreprise.',
  },
  agn: {
    id: 'agn',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'avis de la gendarmerie nationale',
    description: "Avis sur l'instruction d'un titre minier  ou d'une demande relative à la police des mines ",
  },
  aim: {
    id: 'aim',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: "avis de l'Ifremer",
    description: 'Avis de l’institut français de recherche pour l’exploitation en mer (IFREMER) dans le cadre d’autorisation en mer.',
  },
  ama: {
    id: 'ama',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: "avis d'un maire",
    description: "Avis du maire, dans le cadre de l’instruction d’un titre ou d'une demande relative à la police des mines.",
  },
  ami: { id: 'ami', dateFin: null, fondamentale: false, unique: false, nom: 'avis du parc naturel marin', description: 'Avis du parc naturel marin dans le cadre d’autorisation en mer.' },
  and: { id: 'and', dateFin: null, fondamentale: true, unique: false, nom: 'décision du juge administratif', description: 'Décision à un contentieux ou à un référé.' },
  ane: {
    id: 'ane',
    dateFin: null,
    fondamentale: true,
    unique: false,
    nom: 'avis de mise en concurrence au JOUE',
    description:
      "Pour les titres miniers H (hydrocarbures), étape par laquelle le ministre chargé des mines publie l'avis de mise en concurrence au Journal officiel de l'Union européenne au frais du demandeur.",
  },
  anf: {
    id: 'anf',
    dateFin: null,
    fondamentale: true,
    unique: false,
    nom: 'avis de mise en concurrence au JORF',
    description:
      "Pour les titres miniers H (hydrocarbures), étape par laquelle le ministre chargé des mines publie l'avis de mise en concurrence au Journal officiel de la République française au frais du demandeur. Pour les titres miniers M (métaux), étape par laquelle le préfet publie l'avis de mise en concurrence au Journal officiel de la République française au frais du demandeur.",
  },
  aof: {
    id: 'aof',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: "avis de l'Office national des forêts",
    description: 'Avis délivré par l’ONF dans le cadre de l’instruction d’un titre minier.\n',
  },
  aop: { id: 'aop', dateFin: null, fondamentale: false, unique: false, nom: "avis de l'Institut national de l'origine et de la qualité", description: '' },
  apd: {
    id: 'apd',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: "Avis et rapport du directeur régional chargé de l'environnement, de l'aménagement et du logement",
    description:
      "Étape par laquelle le DREAL ou le DEAL rend un avis sur la demande. Cet avis tient compte du rapport rédigé par le service instructeur de la DREAL ou de la DEAL qui s'appuie sur les avis émis par les chefs des services civils et de l'autorité militaire intéressés sur la demande.",
  },
  ape: {
    id: 'ape',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: "avis du Conseil d'Etat",
    description:
      "Le conseil d’État donne au premier ministre et au ministre chargé des mines un avis sur la demande et sur son instruction. Cet avis n'est pas conforme mais si la décision s'écarte de l'avis donné, elle doit être validée en conseil des ministres.",
  },
  api: { id: 'api', dateFin: null, fondamentale: false, unique: false, nom: "avis de l'état major orpaillage et pêche illicite (EMOPI)", description: 'Avis pour tous les titres miniers en Guyane.' },
  apl: { id: 'apl', dateFin: null, fondamentale: false, unique: false, nom: "avis d'un service administratif local", description: '' },
  apm: {
    id: 'apm',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: "avis de l'autorité militaire",
    description: "Avis de l’autorité militaire, délivré dans le cadre de l’instruction d’un titre minier ou d'une demande relative à la police des mines.",
  },
  apn: {
    id: 'apn',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'avis du parc national',
    description: "Avis du parc national dans le cadre de l’instruction d’un titre ou d'une demande relative à la police des mines.",
  },
  apo: {
    id: 'apo',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'avis de la commission départementale des mines (CDM)',
    description: 'L’avis de cette commission est consultatif et donne lieu à des votes des différents membres des collèges. Les représentants des administrations participent également.',
  },
  app: {
    id: 'app',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'avis du préfet',
    description:
      'Le préfet émet un avis à l’issue de l’instruction du dossier, prenant en compte les avis délivrés par les services déconcentrés et éventuellement, l’avis de la commission des mines en Guyane.',
  },
  apu: {
    id: 'apu',
    dateFin: null,
    fondamentale: false,
    unique: true,
    nom: "publication de l'avis de décision implicite",
    description:
      'Le principe adopté par la réglementation actuelle veut que le silence de l’administration pendant un délai fixé vaut accord implicite. Toutefois il existe des décisions implicites de rejets pour certaines catégories de décisions. En particulier pour les titres miniers, l’octroi, la prolongation et la mutation. Les décisions de rejet ne sont pas publiées, les décisions d’acceptation doivent faire l’objet d’un avis au JORF confirmant que cette dernière est acquise. ',
  },
  apw: { id: 'apw', dateFin: null, fondamentale: false, unique: false, nom: 'avis du préfet maritime', description: 'Avis pour les titres miniers en mer.' },
  ari: { id: 'ari', dateFin: null, fondamentale: false, unique: false, nom: 'avis de la réunion interservice', description: '' },
  ars: {
    id: 'ars',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: "avis de l'agence régionale de santé",
    description: "Avis concernant leur respect de la réglementation sanitaire dans le cadre de l'instruction d'un titre minier ou d'une demande relative à la police des mines.",
  },
  asl: { id: 'asl', dateFin: null, fondamentale: false, unique: false, nom: 'décision du propriétaire du sol', description: '' },
  ass: {
    id: 'ass',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'avis de la caisse générale de sécurité sociale',
    description: "Avis émis par le service de la sécurité sociale sur la situation sociale de l'entreprise.",
  },
  auc: {
    id: 'auc',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'avis DGTM service aménagement, urbanisme, construction, logement (AUCL)',
    description: 'Avis de l’AUCL sur la notice d’impact pour les titres miniers et les autorisations d’exploitation. ',
  },
  cac: { id: 'cac', dateFin: null, fondamentale: false, unique: false, nom: 'consultation des administrations centrales', description: '' },
  ccs: {
    id: 'ccs',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'consultation CLE du SAGE',
    description: `consultation de la Commission Locale de L'Eau du Schéma d'Aménagement et de Gestion des Eaux`,
  },
  cim: {
    id: 'cim',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'concertation interministérielle',
    description: 'Concertation prévue dans le cadre des exploitations de granulats marins par les ministères concernés.',
  },
  cod: {
    id: 'cod',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: "saisine du conseil départemental de l'environnement et des risques sanitaires et technologiques  (Coderst)",
    description: '',
  },
  cps: { id: 'cps', dateFin: null, fondamentale: false, unique: false, nom: "confirmation de l'accord du propriétaire du sol", description: '' },
  css: { id: 'css', dateFin: null, fondamentale: false, unique: true, nom: 'classement sans suite', description: '' },
  dae: { id: 'dae', dateFin: null, fondamentale: false, unique: false, nom: 'décision de la mission autorité environnementale (examen au cas par cas du projet)', description: '' },
  dec: { id: 'dec', dateFin: null, fondamentale: false, unique: true, nom: 'déclaration', description: '' },
  def: {
    id: 'def',
    dateFin: toCaminoDate('2018-10-22'),
    fondamentale: true,
    unique: true,
    nom: "décision de l'Office national des forêts",
    description: 'Décision de l’ONF dans le cadre des autorisations d’exploitation (AEX) et des autorisations de recherches minières (ARM) en tant que propriétaire du sol.',
  },
  des: {
    id: 'des',
    dateFin: null,
    fondamentale: false,
    unique: true,
    nom: 'désistement du demandeur',
    description:
      'Le demandeur signifie son souhait de ne pas donner suite à sa demande. Le désistement met fin à la démarche. Le demandeur ne peut pas se désister de sa demande après qu’une décision ait été rendue sur celle-ci.',
  },
  dex: { id: 'dex', dateFin: null, fondamentale: true, unique: false, nom: "décision de l'administration", description: '' },
  dim: {
    id: 'dim',
    dateFin: null,
    fondamentale: true,
    unique: false,
    nom: 'décision implicite',
    description:
      'En dehors des décisions implicites, l’autorité administrative compétente (préfet, ministre chargé des mines ou gouvernement) peut prendre une décision express de refus ou d’acceptation par arrêté ou décret en conseil d’État (décision relative aux concessions minières).',
  },
  dpu: {
    id: 'dpu',
    dateFin: null,
    fondamentale: true,
    unique: false,
    nom: 'publication de décision au JORF',
    description:
      'En dehors des refus et décisions implicites de rejet, la décision de l’autorité compétente est publiée soit au recueil administratif de la préfecture soit au JORF pour les décisions du préfet et au JORF pour celle du ministre chargé des mines et du gouvernement. Ces publications pour les actes relatifs aux titres miniers sont publiés par extrait.',
  },
  dup: {
    id: 'dup',
    dateFin: null,
    fondamentale: true,
    unique: false,
    nom: 'publication de décision administrative au JORF',
    description:
      'A la fin d’une instruction, la décision administrative est publiée au JORF  si elle est positive. Pour les instructions relatives aux granulats marins, la décision administrative est publiée au JORF, qu’elle soit positive ou négative.',
  },
  dux: { id: 'dux', dateFin: null, fondamentale: true, unique: false, nom: 'décision administrative', description: 'Refus ou acceptation à l’issue d’une instruction.' },

  ede: {
    id: 'ede',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'expertise DREAL ou DGTM service eau',
    description: 'Instruction de demande sur la réglementation ayant trait à l’eau par les services de la DGTM.\n',
  },
  edm: { id: 'edm', dateFin: null, fondamentale: false, unique: false, nom: 'expertise DGTM service prévention des risques et industries extractives (DATE)', description: '' },
  eof: {
    id: 'eof',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: "expertise de l'Office national des forêts",
    description: 'Expertise effectuée par l’ONF dans le cadre d’une demande d’autorisation de recherches minières (ARM).',
  },
  epc: { id: 'epc', dateFin: null, fondamentale: false, unique: false, nom: "clôture de l'enquête publique", description: 'L’enquête publique dure un mois. Il est possible de la prolonger. ' },
  epu: {
    id: 'epu',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: "ouverture de l'enquête publique",
    description: 'L’enquête publique requise pour l’octroi des concessions minières et des permis d’exploitations dans les départements d’outre-mer a lieu après constat de recevabilité du dossier.',
  },
  esb: {
    id: 'esb',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'expertise DREAL ou DGTM service biodiversité',
    description: 'Instruction de demande sur la réglementation ayant trait à la biodiversité par les services de la DGTM.',
  },
  ide: {
    id: 'ide',
    dateFin: null,
    fondamentale: false,
    unique: true,
    nom: 'initiation de la démarche de retrait',
    description: 'Initiative de l’administration qui marque l’engagement d’une démarche de retrait.',
  },
  ihi: {
    id: 'ihi',
    dateFin: toCaminoDate('2018-12-31'),
    fondamentale: true,
    unique: true,
    nom: 'informations historiques incomplètes',
    description: 'Impossibilité de retracer la totalité de la vie administrative du titre.',
  },
  mca: { id: 'mca', dateFin: null, fondamentale: false, unique: false, nom: 'demande de compléments (recevabilité de la demande)', description: 'après une mcr' },
  mcb: { id: 'mcb', dateFin: null, fondamentale: false, unique: false, nom: "demande de compléments (récépissé de déclaration loi sur l'eau)", description: 'après une rde' },
  mcd: {
    id: 'mcd',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'demande de compléments (décision de la mission autorité environnementale (examen au cas par cas du projet)',
    description: 'après une dae',
  },
  mcm: { id: 'mcm', dateFin: null, fondamentale: false, unique: false, nom: 'demande de compléments (complétude de la demande)', description: 'après une mcp' },
  mco: {
    id: 'mco',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'demande de compléments',
    description:
      "Étape à l'initiative du service instructeur qui demande des compléments au demandeur et lui fixe un délai maximum pour les transmettre. Cette étape interrompt le décompte du délai dans lequel une décision doit être prise. Cette demande doit faire l'objet d'une lettre recommandée avec demande d'accusé de réception.",
  },
  mcp: {
    id: 'mcp',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'complétude de la demande',
    description:
      'Phase d’examen qui permet d’établir que toutes les pièces exigées par la réglementation sont bien fournies par le demandeur. Cet examen ne préjuge pas de la décision qui sera apportée par l’administration. ',
  },
  mcr: {
    id: 'mcr',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'recevabilité de la demande',
    description:
      'Acte de l’administration établissant que l’examen de complétude a été mené à bien. Le constat de recevabilité donne lieu à un rapport de la part de l’administration qui constate que le dossier de demande est complet. ',
  },
  mcs: { id: 'mcs', dateFin: null, fondamentale: false, unique: false, nom: 'demande de compléments (saisine de la CARM)', description: 'après une sca' },
  mdp: {
    id: 'mdp',
    dateFin: null,
    fondamentale: false,
    unique: true,
    nom: 'dépôt de la demande',
    description:
      "Le dépôt de la demande formalise la prise en charge de la demande par l'administration compétente. Cette étape fait l’objet d’un accusé de réception qui informe le demandeur des modalités d’instruction, du délai au-delà duquel une décision implicite d’accord ou de rejet sera formée et des voies de recours.",
  },
  mec: {
    id: 'mec',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'avis de demande concurrente',
    description: 'Annonce à un demandeur qu’une demande concurrente à la sienne a été déposée.',
  },
  men: {
    id: 'men',
    dateFin: toCaminoDate('2018-01-01'),
    fondamentale: false,
    unique: true,
    nom: 'enregistrement de la demande',
    description: "L’enregistrement de la demande est une étape de gestion administrative interne du dossier qui se confond au dépôt de la demande lorsqu'elle est numérique et dématérialisée.",
  },
  meo: { id: 'meo', dateFin: toCaminoDate('2020-01-01'), fondamentale: false, unique: true, nom: "prise en charge par l'Office national des forêts", description: '' },
  mfr: {
    id: 'mfr',
    dateFin: null,
    fondamentale: true,
    unique: true,
    nom: 'demande',
    description:
      'La demande caractérise le projet minier porté par le demandeur. Elle inclut les caractéristiques fondamentales du titre ou de l’autorisation dans une lettre appuyée par un dossier et les justifications des capacités techniques et financières. Les informations relevant du secret des affaires incluses à la demande peuvent ne pas être rendues publiques à la demande du porteur de projet.',
  },
  mia: { id: 'mia', dateFin: null, fondamentale: false, unique: false, nom: "demande d'informations (avis de l'Office national des forêts)", description: 'après une aof' },
  mie: { id: 'mie', dateFin: null, fondamentale: false, unique: false, nom: "demande d'informations (avis du DREAL, DEAL ou DGTM)", description: 'après une adp' },
  mif: {
    id: 'mif',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: "demande d'informations",
    description: "Étape à l'initiative du service instructeur pour obtenir des informations qui ne sont pas de nature à interrompre le décompte du délai dans lequel une décision doit être prise. \n",
  },
  mim: { id: 'mim', dateFin: null, fondamentale: false, unique: false, nom: "demande d'informations (recevabilité de la demande)", description: 'après une mcr' },
  mio: { id: 'mio', dateFin: null, fondamentale: false, unique: false, nom: "demande d'informations (expertise de l'Office national des forêts)", description: 'après une eof' },
  mna: { id: 'mna', dateFin: null, fondamentale: false, unique: false, nom: 'notification au demandeur (ajournement de la CARM)', description: 'après une aca ajournée' },
  mnb: { id: 'mnb', dateFin: null, fondamentale: false, unique: false, nom: 'notification au demandeur (avis favorable de la CARM)', description: 'après une aca favorable' },
  mnc: { id: 'mnc', dateFin: null, fondamentale: false, unique: false, nom: 'notification au demandeur (classement sans suite)', description: 'après une css' },
  mnd: { id: 'mnd', dateFin: null, fondamentale: false, unique: false, nom: 'notification au demandeur (avis défavorable)', description: 'après une aca défavorable' },
  mni: { id: 'mni', dateFin: null, fondamentale: false, unique: false, nom: 'notification au demandeur (initiation de la démarche de retrait)', description: 'après une ide' },
  mno: { id: 'mno', dateFin: null, fondamentale: false, unique: false, nom: 'notification au demandeur', description: 'Notification de la décision au demandeur.' },
  mns: { id: 'mns', dateFin: null, fondamentale: false, unique: false, nom: 'notification au demandeur (signature de l’autorisation de recherche minière)', description: 'après une sco' },
  mnv: { id: 'mnv', dateFin: null, fondamentale: false, unique: false, nom: "notification au demandeur (signature de l'avenant à l’autorisation de recherche minière)", description: 'après une aco' },
  mod: {
    id: 'mod',
    dateFin: null,
    fondamentale: true,
    unique: false,
    nom: 'modification de la demande',
    description:
      'Le porteur modifie les caractéristiques fondamentales de sa demande. Cette modification ne change pas le délai de décision implicite. Les possibilités sont limitées au gré de l’avancement de la démarche, en particulier après la mise en concurrence et après la participation du public.\n',
  },
  mom: {
    id: 'mom',
    dateFin: null,
    fondamentale: true,
    unique: false,
    nom: 'modification de la demande (décision de la mission autorité environnementale (examen au cas par cas du projet)',
    description: 'après une dae',
  },
  ncl: { id: 'ncl', dateFin: null, fondamentale: false, unique: false, nom: 'notification des collectivités locales', description: 'Notification de la décision aux collectivités locales.' },
  nis: {
    id: 'nis',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'note interne signalée',
    description: "Note confidentielle qui permet de faire connaître au sein de l'administration un certain nombre d'informations importantes. \n",
  },
  npp: {
    id: 'npp',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'notification au préfet',
    description: 'Note au préfet demandant de notifier la décision à l’intéressé et de prendre les mesures de publicité nécessaires.',
  },
  pfc: {
    id: 'pfc',
    dateFin: null,
    fondamentale: false,
    unique: true,
    nom: 'paiement des frais de dossier complémentaires',
    description: 'Supplément de frais de dossier concernant uniquement les ARM mécanisées car elles nécessitent une expertise complémentaire (état des lieux par imagerie).\n',
  },
  pfd: { id: 'pfd', dateFin: null, fondamentale: false, unique: true, nom: 'paiement des frais de dossier', description: '' },
  pnr: {
    id: 'pnr',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'avis du parc naturel régional',
    description: "Avis du parc naturel régional dans le cadre de l’instruction d’un titre ou d'une demande relative à la police des mines.",
  },
  ppc: {
    id: 'ppc',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'clôture de la participation du public',
    description:
      'La durée de la participation du public doit être au moins égale 15 jours. L’administration doit tenir compte pour sa décision des avis recueillis lors de la participation du public.',
  },
  ppu: {
    id: 'ppu',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'ouverture de la participation du public',
    description:
      'La participation du public est obligatoire pour l’octroi des permis exclusifs de recherches (PER) et les prolongations de concessions minières. La législation ne prévoit pas à quel moment elle intervient. Il a été décidé pour les titres miniers qu’elle aurait lieu dès la déclaration de recevabilité du dossier. ',
  },
  pqr: { id: 'pqr', dateFin: null, fondamentale: false, unique: false, nom: 'publication dans un journal local ou national', description: '' },
  rca: { id: 'rca', dateFin: null, fondamentale: true, unique: false, nom: 'réception de compléments (recevabilité de la demande)', description: 'après une mcr' },
  rcb: { id: 'rcb', dateFin: null, fondamentale: true, unique: false, nom: "réception de compléments (récépissé de déclaration loi sur l'eau)", description: 'après une rde' },
  rcd: {
    id: 'rcd',
    dateFin: null,
    fondamentale: true,
    unique: false,
    nom: 'réception de compléments (décision de la mission autorité environnementale (examen au cas par cas du projet))',
    description: 'après une dae',
  },
  rcg: { id: 'rcg', dateFin: null, fondamentale: false, unique: false, nom: "rapport du conseil général de l'économie (CGE)", description: '' },
  rcm: { id: 'rcm', dateFin: null, fondamentale: true, unique: false, nom: 'réception de compléments (complétude de la demande)', description: 'après une mcp' },
  rco: {
    id: 'rco',
    dateFin: null,
    fondamentale: true,
    unique: false,
    nom: 'réception de compléments',
    description:
      'Étape par laquelle le service instructeur accuse réception des compléments transmis par le demandeur. Cette étape permet la reprise du décompte du délai dans lequel une décision doit être prise.',
  },
  rcs: { id: 'rcs', dateFin: null, fondamentale: true, unique: false, nom: 'réception de compléments (saisine de la CARM)', description: 'après une sca' },
  rde: {
    id: 'rde',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: "récépissé de déclaration loi sur l'eau",
    description: 'Document nécessaire à l’utilisation de l’eau dans le cas d’une autorisation de recherches minières (ARM).',
  },
  ria: { id: 'ria', dateFin: null, fondamentale: true, unique: false, nom: "réception d'information (avis de l'Office national des forêts)", description: 'après une aof' },
  rie: { id: 'rie', dateFin: null, fondamentale: true, unique: false, nom: "réception d'information (avis du DREAL, DEAL ou DGTM)", description: 'après une adp' },
  rif: { id: 'rif', dateFin: null, fondamentale: true, unique: false, nom: "réception d'information", description: "Étape par laquelle le service instructeur reçoit l'information demandée." },
  rim: { id: 'rim', dateFin: null, fondamentale: true, unique: false, nom: "réception d'information (recevabilité de la demande)", description: 'après une mcr' },
  rio: { id: 'rio', dateFin: null, fondamentale: true, unique: false, nom: "réception d'information (expertise de l'Office national des forêts)", description: 'après une eof' },
  rpe: { id: 'rpe', dateFin: null, fondamentale: false, unique: false, nom: 'rapport du Conseil d’État', description: '' },
  rpu: {
    id: 'rpu',
    dateFin: null,
    fondamentale: true,
    unique: false,
    nom: 'publication de décision au recueil des actes administratifs',
    description: 'Publication, par le préfet, au recueil des actes administratifs.',
  },
  rtd: {
    id: 'rtd',
    dateFin: null,
    fondamentale: true,
    unique: false,
    nom: 'retrait de la décision',
    description: 'Sanction administrative consistant à retirer le titre minier dans les cas énumérés dans le code minier.',
  },
  sas: { id: 'sas', dateFin: null, fondamentale: false, unique: false, nom: "saisine de l'autorité signataire", description: '' },
  sca: { id: 'sca', dateFin: null, fondamentale: false, unique: false, nom: 'saisine de la commission des autorisations de recherches minières (CARM)', description: '' },
  scg: {
    id: 'scg',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: "saisine du conseil général de l'économie (CGE)",
    description:
      "Étape par laquelle le service instructeur transmet la demande, les différents avis et une proposition de décision du ministre chargé des mines au conseil général de l'économie pour avis.",
  },
  scl: {
    id: 'scl',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'saisine des collectivités locales',
    description: 'Consultation pour avis, des collectivités locales dans le cadre de l’instruction d’un titre ou d’une autorisation.',
  },
  sco: {
    id: 'sco',
    dateFin: null,
    fondamentale: true,
    unique: true,
    nom: 'signature de l’autorisation de recherche minière',
    description:
      'Signature de l’autorisation par l’ONF seulement dans le cas d’ARM manuelles ou par les deux parties (ONF et demandeur) dans le cas d’ARM mécanisées pour acceptation de l’état des lieux par le demandeur et valant début de validité de celle-ci.',
  },
  spe: {
    id: 'spe',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: "saisine du Conseil d'Etat",
    description: 'Le service instructeur transmet la demande, les différents avis et une proposition de décision du premier ministre et du ministre chargé des mines au conseil d’État pour avis.',
  },
  spo: {
    id: 'spo',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'saisine de la commission départementale des mines (CDM)',
    description:
      'Dans les seuls départements d’Outre-mer (Guadeloupe, Guyane, Réunion, Martinique et Mayotte) une commission dédiée à l’examen des demandes minières se réunit comportant les différentes parties prenantes. Cette commission donne un avis consultatif sur le rapport des services déconcentrés. Pour l’instant, cette commission se réunit uniquement en Guyane.',
  },
  spp: {
    id: 'spp',
    dateFin: null,
    fondamentale: false,
    unique: true,
    nom: 'saisine du préfet',
    description: 'L’administration centrale transmet la demande au préfet pour qu’il engage son instruction locale.\n',
  },
  ssr: {
    id: 'ssr',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: 'saisine des services',
    description:
      'Demande de consultation dans le cadre d’un titre minier des chefs de service civils et de l’autorité militaire. Les intéressés ont un mois pour répondre. Au-delà de ce délai,  le silence vaut accord.\n',
  },
  vfc: {
    id: 'vfc',
    dateFin: null,
    fondamentale: false,
    unique: true,
    nom: 'validation du paiement des frais de dossier complémentaires',
    description: 'Validation par la direction générale des territoires et des mines (DGTM).',
  },
  vfd: {
    id: 'vfd',
    dateFin: null,
    fondamentale: false,
    unique: true,
    nom: 'validation du paiement des frais de dossier',
    description: 'Acte attestant que le pétitionnaire d’une autorisation de recherches minières (ARM) a acquitté ses frais de dossier.\n',
  },
  wab: { id: 'wab', dateFin: null, fondamentale: false, unique: false, nom: 'Abandon de la demande', description: '' },
  wac: { id: 'wac', dateFin: null, fondamentale: false, unique: false, nom: 'avis de direction régionale des affaires culturelles - DRAC', description: '' },
  wad: { id: 'wad', dateFin: null, fondamentale: false, unique: false, nom: 'avis de la direction départementale des territoires et de la mer - DDT(M)', description: '' },
  wae: { id: 'wae', dateFin: null, fondamentale: false, unique: false, nom: "avis de l'autorité environnementale", description: '' },
  wai: { id: 'wai', dateFin: null, fondamentale: false, unique: false, nom: 'avis des autres instances', description: '' },
  wal: { id: 'wal', dateFin: null, fondamentale: false, unique: false, nom: "avis d'un service administratif local", description: '' },
  wam: { id: 'wam', dateFin: null, fondamentale: false, unique: false, nom: "avis de l'autorité militaire", description: '' },
  wao: { id: 'wao', dateFin: null, fondamentale: false, unique: false, nom: "arrêté d'ouverture des travaux miniers", description: "Arrêté d'ouverture des travaux miniers" },
  wap: { id: 'wap', dateFin: null, fondamentale: false, unique: false, nom: 'avis du préfet maritime', description: '' },
  war: { id: 'war', dateFin: null, fondamentale: false, unique: false, nom: 'avis de réception', description: '' },
  was: { id: 'was', dateFin: null, fondamentale: false, unique: false, nom: "avis de l'agence régionale de santé - ARS", description: '' },
  wat: { id: 'wat', dateFin: null, fondamentale: false, unique: false, nom: "avis du conseil départemental de l'environnement et des risques sanitaires et technologiques (Coderst)", description: '' },
  wau: { id: 'wau', dateFin: null, fondamentale: false, unique: false, nom: 'Avis du demandeur sur les prescriptions proposées', description: '' },
  wce: { id: 'wce', dateFin: null, fondamentale: false, unique: false, nom: "clôture de l'enquête publique", description: '' },
  wco: { id: 'wco', dateFin: null, fondamentale: false, unique: false, nom: 'Réception de compléments', description: '' },
  wda: { id: 'wda', dateFin: null, fondamentale: false, unique: false, nom: 'Donné acte de la déclaration (DOTM)', description: '' },
  wdc: { id: 'wdc', dateFin: null, fondamentale: false, unique: false, nom: 'demande de compléments (AOTM ou DOTM)', description: '' },
  wdd: { id: 'wdd', dateFin: null, fondamentale: false, unique: false, nom: 'dépot de la demande', description: '' },
  wde: { id: 'wde', dateFin: null, fondamentale: false, unique: false, nom: 'demande de compléments (DADT)', description: '' },
  wdm: { id: 'wdm', dateFin: null, fondamentale: false, unique: false, nom: "décision de l'administration", description: '' },
  wdt: { id: 'wdt', dateFin: null, fondamentale: false, unique: false, nom: 'avis de la DDT(M)', description: 'avis de la Direction Départementale des Territoires et de la Mer' },
  wfa: { id: 'wfa', dateFin: null, fondamentale: false, unique: false, nom: "Demande d'autorisation d'ouverture de travaux miniers (AOTM)", description: '' },
  wfd: { id: 'wfd', dateFin: null, fondamentale: false, unique: false, nom: "Déclaration d'arrêt définitif de travaux (DADT)", description: '' },
  wfo: { id: 'wfo', dateFin: null, fondamentale: false, unique: false, nom: "Déclaration d'ouverture de travaux miniers (DOTM)", description: '' },
  wfr: { id: 'wfr', dateFin: null, fondamentale: false, unique: false, nom: "Demande d'autorisation d'ouverture de travaux miniers (DAOTM)", description: '' },
  wmm: { id: 'wmm', dateFin: null, fondamentale: false, unique: false, nom: "memoire en réponse de l'exploitant (par rapport à l'avis de l'AE)", description: '' },
  wmr: {
    id: 'wmr',
    dateFin: null,
    fondamentale: false,
    unique: false,
    nom: "mémoire en réponse de l'exploitant",
    description: "mémoire en réponse de l'exploitant à l'avis d'autorité environnementale.",
  },
  wmt: { id: 'wmt', dateFin: null, fondamentale: false, unique: false, nom: 'memoire de fin de travaux', description: '' },
  woe: { id: 'woe', dateFin: null, fondamentale: false, unique: false, nom: "ouverture de l'enquête publique", description: '' },
  wpa: { id: 'wpa', dateFin: null, fondamentale: false, unique: false, nom: 'publication de décision au recueil des actes administratifs', description: '' },
  wpb: { id: 'wpb', dateFin: null, fondamentale: false, unique: false, nom: 'porter-à-connaissance', description: 'Porter-à-connaissance' },
  wpc: { id: 'wpc', dateFin: null, fondamentale: false, unique: false, nom: 'Arrêté de prescriptions complémentaires', description: '' },
  wpo: { id: 'wpo', dateFin: null, fondamentale: false, unique: false, nom: 'Arrêté de second donner acte', description: '' },
  wpp: { id: 'wpp', dateFin: null, fondamentale: false, unique: false, nom: 'Arrêté préfectoral de premier donner acte (DADT)', description: '' },
  wps: { id: 'wps', dateFin: null, fondamentale: false, unique: false, nom: 'Arrêté préfectoral de sursis à statuer', description: '' },
  wrc: { id: 'wrc', dateFin: null, fondamentale: false, unique: false, nom: 'reception de compléments', description: '' },
  wrd: { id: 'wrd', dateFin: null, fondamentale: false, unique: false, nom: 'Rapport de la Dreal', description: '' },
  wre: { id: 'wre', dateFin: null, fondamentale: false, unique: false, nom: 'Recevabilité', description: '' },
  wrl: { id: 'wrl', dateFin: null, fondamentale: false, unique: false, nom: "Avis et rapport du directeur régional chargé de l'environnement, de l'aménagement et du logement", description: '' },
  wrt: { id: 'wrt', dateFin: null, fondamentale: false, unique: false, nom: 'récolement', description: '' },
  wse: { id: 'wse', dateFin: null, fondamentale: false, unique: false, nom: "saisine de l'autorité environnementale", description: '' },
  wss: { id: 'wss', dateFin: null, fondamentale: false, unique: false, nom: "saisine des services de l'Etat", description: '' },
  wtp: { id: 'wtp', dateFin: null, fondamentale: false, unique: false, nom: 'Transmission du projet de prescriptions au demandeur', description: '' },
}

export const isEtapeTypeId = (etapeTypeId: string): etapeTypeId is EtapeTypeId => {
  return etapesTypesIds.includes(etapeTypeId)
}
export const isEtapeTypeKey = (etapeTypeKey: string): etapeTypeKey is EtapeTypeKey => {
  return etapeTypeKey in ETAPES_TYPES
}
