---
- name: Ajout utilisateurs
  include_tasks: "devs.yml"
  loop: "{{ users }}"
  loop_control:
    loop_var: camino_dev
- name: ajoute le groupe "git"
  ansible.builtin.group:
    name: git
    state: present
    gid: "{{ git_user_uid }}"
  become: True
- name: ajoute l'utilisateur 'git'
  ansible.builtin.user:
    name: git
    comment: Git
    # L'UID doit être le même que dans le Dockerfile.api
    uid: "{{ git_user_uid }}"
    groups: git, users, docker
  become: True
- file:
    path: /srv/www/camino/files
    group: users
    state: directory
    recurse: True
    owner: git
    mode: u=rwx,g=rwx,o=r
  become: True