#!/bin/bash
set eufo -pipefail

if [ "$(id -u)" != "{{git_user_uid}}" ]; then
   echo "This script must be run as git" 1>&2
   exit 1
fi
# backup

# sauvegarde la base de donnees
rm -rf /srv/backups/camino.sql
docker exec camino_api_db pg_dump --clean --if-exists --format=c --no-owner --no-privileges --dbname=camino > /srv/backups/camino.sql

# sauvegarde les fichiers
rsync --delete -r /srv/www/camino/files/  /srv/backups/files
chown git:users -R /srv/backups/


export RESTIC_REPOSITORY=s3:https://b3.din.developpement-durable.gouv.fr/Camino
export RESTIC_PASSWORD={{ restic_password }}
# Environnement B3 (Identifiant)
export AWS_ACCESS_KEY_ID={{ restic_s3_client_id }}
export AWS_SECRET_ACCESS_KEY={{ restic_s3_client_secret }}


restic backup /srv/backups/