#!/bin/bash
set eufo -pipefail

source /srv/scripts/restic_data

if [ "$(id -u)" != "{{git_user_uid}}" ]; then
   echo "This script must be run as git" 1>&2
   exit 1
fi
# backup

# sauvegarde la base de donnees
rm -rf /srv/backups/camino.sql
docker exec camino_api_db pg_dump --clean --if-exists --format=c --no-owner --no-privileges --dbname=camino > /srv/backups/camino.sql

# sauvegarde les fichiers
rsync --delete -r /srv/www/camino/files/  /srv/backups/files
chown git:users -R /srv/backups/

restic backup /srv/backups/