#!/bin/bash
set eufo -pipefail

if [ "$(id -u)" != "{{git_user_uid}}" ]; then
   echo "This script must be run as git" 1>&2
   exit 1
fi

docker exec camino_api_db pg_dump --clean --if-exists --format=c --no-owner --no-privileges --dbname=camino > /srv/backups/camino_for_transfer.sql

chown git:users /srv/backups/camino_for_transfer.sql

scp -P 212 /srv/backups/camino_for_transfer.sql prod@preprod.camino.beta.gouv.fr:/srv/backups/camino_prod.sql
rsync -avz --delete -e 'ssh -p 212' /srv/www/camino/files prod@preprod.camino.beta.gouv.fr:/srv/backups/camino_prod/

scp -P 212 /srv/backups/camino_for_transfer.sql prod@dev.camino.beta.gouv.fr:/srv/backups/camino_prod.sql
rsync -avz --delete -e 'ssh -p 212' /srv/www/camino/files prod@dev.camino.beta.gouv.fr:/srv/backups/camino_prod/