#!/bin/bash

scp -P 212 /srv/backups/camino.sql prod@preprod.camino.beta.gouv.fr:/srv/backups/camino_prod.sql
rsync -avz --delete -e 'ssh -p 212' /srv/www/camino/files prod@preprod.camino.beta.gouv.fr:/srv/backups/camino_prod/

scp -P 212 /srv/backups/camino.sql prod@dev.camino.beta.gouv.fr:/srv/backups/camino_prod.sql
rsync -avz --delete -e 'ssh -p 212' /srv/www/camino/files prod@dev.camino.beta.gouv.fr:/srv/backups/camino_prod/