// Generated by 'scripts/generateIconTypes.ts', DO NOT MODIFY MANUALLY
// add new icons in the iconSprite.svg and run 'npm run generate-icon-types -w packages/ui', or commit and husky will do it
export const icons = [
  'checkbox',
  'checkbox-blank',
  'chevron-bas',
  'chevron-haut',
  'close',
  'download',
  'error-warning',
  'help',
  'plus',
  'refresh',
  'x'
] as const
export type Icon = typeof icons[number]
