// Generated by 'scripts/generateIconTypes.ts', DO NOT MODIFY MANUALLY
// add new icons in the iconSprite.svg and run 'npm run generate-icon-types -w packages/ui', or commit and husky will do it
export const icons = [
  'chevron-bas',
  'chevron-haut',
  'close',
  'download'
] as const
export type Icon = typeof icons[number]
