---
- name: Ajoute le script de backup
  ansible.builtin.template:
    src: backup
    dest: /srv/scripts/
    mode: u=rwx,g=rx,o=r
    owner: git
    group: users
    backup: yes
  become: True
- name: Ajoute le job de backup de la prod
  ansible.builtin.cron:
    name: "backup"
    minute: "0"
    hour: "2"
    job: "/srv/scripts/backup"
    user: git
  become: True