import { Definition } from './definition'
import { RegionId } from './region'
import { DepartementId } from './departement'

export const ADMINISTRATION_TYPE_IDS = {
  AUTORITE: 'aut',
  DEAL: 'dea',
  DREAL: 'dre',
  MINISTERE: 'min',
  OPERATEUR: 'ope',
  PREFECTURE: 'pre'
} as const

export type AdministrationTypeId =
  typeof ADMINISTRATION_TYPE_IDS[keyof typeof ADMINISTRATION_TYPE_IDS]

export type AdministrationType<T = AdministrationTypeId> = Omit<
  Definition<T>,
  'description'
>
export const ADMINISTRATION_TYPES: {
  [key in AdministrationTypeId]: AdministrationType<key>
} = {
  aut: {
    id: 'aut',
    nom: 'Autorité',
    ordre: 6
  },
  dea: {
    id: 'dea',
    nom: 'Déal',
    ordre: 3
  },
  dre: {
    id: 'dre',
    nom: 'Dréal',
    ordre: 2
  },
  min: {
    id: 'min',
    nom: 'Ministère',
    ordre: 1
  },
  ope: {
    id: 'ope',
    nom: 'Opérateur',
    ordre: 5
  },
  pre: {
    id: 'pre',
    nom: 'Préfecture',
    ordre: 4
  }
}

export const sortedAdministrationTypes = Object.values(
  ADMINISTRATION_TYPES
).sort((a, b) => a.ordre - b.ordre)

export const ADMINISTRATION_IDS = {
  'GENDARMERIE NATIONALE - GUYANE': 'aut-97300-01',
  'MRAE GUYANE': 'aut-mrae-guyane-01',
  'DEAL - GUADELOUPE': 'dea-guadeloupe-01',
  'DGTM - GUYANE': 'dea-guyane-01',
  'DEAL - MARTINIQUE': 'dea-martinique-01',
  'DEAL - MAYOTTE': 'dea-mayotte-01',
  'DEAL - LA RÉUNION': 'dea-reunion-01',
  'DREAL - AUVERGNE-RHÔNE-ALPES - SIÈGE DE LYON': 'dre-aura-01',
  'DREAL - BOURGOGNE-FRANCHE-COMTÉ - SIÈGE DE BESANÇON': 'dre-bfc-01',
  'DREAL - BRETAGNE': 'dre-bretagne-01',
  'DREAL - CENTRE-VAL-DE-LOIRE': 'dre-centre-val-de-loire-01',
  'DREAL - CORSE': 'dre-corse-01',
  'DREAL - GRAND EST - SIÈGE DE METZ': 'dre-grand-est-01',
  'DREAL - HAUTS-DE-FRANCE - SIÈGE DE LILLE': 'dre-hauts-de-france-01',
  'DRIEE - ÎLE-DE-FRANCE': 'dre-ile-de-france-01',
  'DREAL - NORMANDIE - SIÈGE DE ROUEN': 'dre-normandie-01',
  'DREAL - NOUVELLE-AQUITAINE - SIÈGE DE POITIERS': 'dre-nouvelle-aquitaine-01',
  'DREAL - OCCITANIE - SIÈGE DE TOULOUSE': 'dre-occitanie-01',
  "DREAL - PROVENCE-ALPES-CÔTE-D'AZUR": 'dre-paca-01',
  'DREAL - PAYS DE LA LOIRE': 'dre-pays-de-la-loire-01',
  "DAJ - MINISTÈRE DE L'ECONOMIE, DES FINANCES ET DE LA RELANCE": 'min-dajb-01',
  'DGCL/SDFLAE/FL1': 'min-mctrct-dgcl-01',
  'DGALN/DEB/EARM2': 'min-mtes-dgaln-01',
  'DGEC/DE/SD2/2A': 'min-mtes-dgec-01',
  'DGPR/SRT/SDRCP/BSSS': 'min-mtes-dgpr-01',
  BRGM: 'ope-brgm-01',
  'BRGM - PROJET ZERCOA': 'ope-brgm-02',
  CACEM: 'ope-cacem-01',
  'OFFICE NATIONAL DES FORÊTS': 'ope-onf-973-01',
  'PÔLE TECHNIQUE MINIER DE GUYANE': 'ope-ptmg-973-01',
  'PRÉFECTURE - AIN': 'pre-01053-01',
  'PRÉFECTURE - AISNE': 'pre-02408-01',
  'PRÉFECTURE - ALLIER': 'pre-03190-01',
  'PRÉFECTURE - ALPES-DE-HAUTE-PROVENCE': 'pre-04070-01',
  'PRÉFECTURE - HAUTES-ALPES': 'pre-05061-01',
  'PRÉFECTURE - ALPES-MARITIMES': 'pre-06088-01',
  'PRÉFECTURE - ARDÈCHE': 'pre-07186-01',
  'PRÉFECTURE - ARDENNES': 'pre-08105-01',
  'PRÉFECTURE - ARIÈGE': 'pre-09122-01',
  'PRÉFECTURE - AUBE': 'pre-10387-01',
  'PRÉFECTURE - AUDE': 'pre-11069-01',
  'PRÉFECTURE - AVEYRON': 'pre-12202-01',
  'PRÉFECTURE - BOUCHES-DU-RHÔNE': 'pre-13203-01',
  'PRÉFECTURE - CALVADOS': 'pre-14118-01',
  'PRÉFECTURE - CANTAL': 'pre-15014-01',
  'PRÉFECTURE - CHARENTE': 'pre-16015-01',
  'PRÉFECTURE - CHARENTE-MARITIME': 'pre-17300-01',
  'PRÉFECTURE - CHER': 'pre-18033-01',
  'PRÉFECTURE - CORRÈZE': 'pre-19272-01',
  "PRÉFECTURE - CÔTE-D'OR": 'pre-21231-01',
  "PRÉFECTURE - CÔTES-D'ARMOR": 'pre-22278-01',
  'PRÉFECTURE - CREUSE': 'pre-23096-01',
  'PRÉFECTURE - DORDOGNE': 'pre-24322-01',
  'PRÉFECTURE - DOUBS': 'pre-25056-01',
  'PRÉFECTURE - DRÔME': 'pre-26362-01',
  'PRÉFECTURE - EURE': 'pre-27229-01',
  'PRÉFECTURE - EURE-ET-LOIR': 'pre-28085-01',
  'PRÉFECTURE - FINISTÈRE': 'pre-29232-01',
  'PRÉFECTURE - CORSE-DU-SUD': 'pre-2A004-01',
  'PRÉFECTURE - HAUTE-CORSE': 'pre-2B033-01',
  'PRÉFECTURE - GARD': 'pre-30189-01',
  'PRÉFECTURE - HAUTE-GARONNE': 'pre-31555-01',
  'PRÉFECTURE - GERS': 'pre-32013-01',
  'PRÉFECTURE - GIRONDE': 'pre-33063-01',
  'PRÉFECTURE - HÉRAULT': 'pre-34172-01',
  'PRÉFECTURE - ILLE-ET-VILAINE': 'pre-35238-01',
  'PRÉFECTURE - INDRE': 'pre-36044-01',
  'PRÉFECTURE - INDRE-ET-LOIRE': 'pre-37261-01',
  'PRÉFECTURE - ISÈRE': 'pre-38185-01',
  'PRÉFECTURE - JURA': 'pre-39300-01',
  'PRÉFECTURE - LANDES': 'pre-40192-01',
  'PRÉFECTURE - LOIR-ET-CHER': 'pre-41018-01',
  'PRÉFECTURE - LOIRE': 'pre-42218-01',
  'PRÉFECTURE - HAUTE-LOIRE': 'pre-43157-01',
  'PRÉFECTURE - LOIRE-ATLANTIQUE': 'pre-44109-01',
  'PRÉFECTURE - LOIRET': 'pre-45234-01',
  'PRÉFECTURE - LOT': 'pre-46042-01',
  'PRÉFECTURE - LOT-ET-GARONNE': 'pre-47001-01',
  'PRÉFECTURE - LOZÈRE': 'pre-48095-01',
  'PRÉFECTURE - MAINE-ET-LOIRE': 'pre-49007-01',
  'PRÉFECTURE - MANCHE': 'pre-50502-01',
  'PRÉFECTURE - MARNE': 'pre-51108-01',
  'PRÉFECTURE - HAUTE-MARNE': 'pre-52121-01',
  'PRÉFECTURE - MAYENNE': 'pre-53130-01',
  'PRÉFECTURE - MEURTHE-ET-MOSELLE': 'pre-54395-01',
  'PRÉFECTURE - MEUSE': 'pre-55029-01',
  'PRÉFECTURE - MORBIHAN': 'pre-56260-01',
  'PRÉFECTURE - MOSELLE': 'pre-57463-01',
  'PRÉFECTURE - NIÈVRE': 'pre-58194-01',
  'PRÉFECTURE - NORD': 'pre-59350-01',
  'PRÉFECTURE - OISE': 'pre-60057-01',
  'PRÉFECTURE - ORNE': 'pre-61001-01',
  'PRÉFECTURE - PAS-DE-CALAIS': 'pre-62041-01',
  'PRÉFECTURE - PUY-DE-DÔME': 'pre-63113-01',
  'PRÉFECTURE - PYRÉNÉES-ATLANTIQUES': 'pre-64445-01',
  'PRÉFECTURE - HAUTES-PYRÉNÉES': 'pre-65440-01',
  'PRÉFECTURE - PYRÉNÉES-ORIENTALES': 'pre-66136-01',
  'PRÉFECTURE - BAS-RHIN': 'pre-67482-01',
  'PRÉFECTURE - HAUT-RHIN': 'pre-68066-01',
  'PRÉFECTURE - RHÔNE': 'pre-69383-01',
  'PRÉFECTURE - HAUTE-SAÔNE': 'pre-70550-01',
  'PRÉFECTURE - SAÔNE-ET-LOIRE': 'pre-71270-01',
  'PRÉFECTURE - SARTHE': 'pre-72181-01',
  'PRÉFECTURE - SAVOIE': 'pre-73065-01',
  'PRÉFECTURE - HAUTE-SAVOIE': 'pre-74010-01',
  'PRÉFECTURE - ÎLE-DE-FRANCE': 'pre-75104-01',
  'PRÉFECTURE - SEINE-MARITIME': 'pre-76540-01',
  'PRÉFECTURE - SEINE-ET-MARNE': 'pre-77288-01',
  'PRÉFECTURE - YVELINES': 'pre-78646-01',
  'PRÉFECTURE - DEUX-SÈVRES': 'pre-79191-01',
  'PRÉFECTURE - SOMME': 'pre-80021-01',
  'PRÉFECTURE - TARN': 'pre-81004-01',
  'PRÉFECTURE - TARN-ET-GARONNE': 'pre-82121-01',
  'PRÉFECTURE - VAR': 'pre-83137-01',
  'PRÉFECTURE - VAUCLUSE': 'pre-84007-01',
  'PRÉFECTURE - VENDÉE': 'pre-85191-01',
  'PRÉFECTURE - VIENNE': 'pre-86194-01',
  'PRÉFECTURE - HAUTE-VIENNE': 'pre-87085-01',
  'PRÉFECTURE - VOSGES': 'pre-88160-01',
  'PRÉFECTURE - YONNE': 'pre-89024-01',
  'PRÉFECTURE - TERRITOIRE DE BELFORT': 'pre-90010-01',
  'PRÉFECTURE - ESSONNE': 'pre-91228-01',
  'PRÉFECTURE - HAUTS-DE-SEINE': 'pre-92050-01',
  'PRÉFECTURE - SEINE-SAINT-DENIS': 'pre-93008-01',
  'PRÉFECTURE - VAL-DE-MARNE': 'pre-94028-01',
  "PRÉFECTURE - VAL-D'OISE": 'pre-95127-01',
  'PRÉFECTURE - GUADELOUPE': 'pre-97105-01',
  'PRÉFECTURE - MARTINIQUE': 'pre-97209-01',
  'PRÉFECTURE - GUYANE': 'pre-97302-01',
  'PRÉFECTURE - RÉUNION': 'pre-97411-01',
  'PRÉFECTURE - MAYOTTE': 'pre-97611-01'
} as const

export type AdministrationId =
  typeof ADMINISTRATION_IDS[keyof typeof ADMINISTRATION_IDS]

export interface Administration<T = AdministrationId> {
  id: T
  typeId: AdministrationTypeId
  nom: string
  abreviation: string
  service?: string
  url?: string
  email?: string
  telephone?: string
  adresse1: string
  adresse2?: string
  codePostal: string
  commune: string
  cedex?: string
  regionId?: RegionId
  departementId?: DepartementId
}

export const Administrations: {
  [key in AdministrationId]: Administration<key>
} = {
  'aut-97300-01': {
    id: 'aut-97300-01',
    typeId: 'aut',
    nom: 'Gendarmerie Nationale - Guyane',
    abreviation: 'Gendarmerie Nationale - Guyane',
    service: 'Centre de conduite des Opérations',
    url: 'https://www.gendarmerie.interieur.gouv.fr/',
    email: 'cco.comgendgf@gendarmerie.interieur.gouv.fr',
    telephone: '+594 29 28 00',
    adresse1: 'Caserne La Madeleine',
    adresse2: '1296 Route de la Madeleine',
    codePostal: '97300',
    commune: 'Cayenne'
  },
  'aut-mrae-guyane-01': {
    id: 'aut-mrae-guyane-01',
    typeId: 'aut',
    nom: 'Mission régionale autorité environnementale de Guyane',
    abreviation: 'MRAE Guyane',
    url: 'http://www.mrae.developpement-durable.gouv.fr/guyane-r27.html',
    telephone: '+594 (0)5 94 39 80 00',
    adresse1: 'Route du Vieux-Port\n97300 Cayenne',
    adresse2: 'Adresse postale\nRoute du Vieux-Port\nCS 76003\n97306 Cayenne',
    codePostal: '97300',
    commune: 'Cayenne',
    cedex: 'Cedex',
    regionId: '03'
  },
  'dea-guadeloupe-01': {
    id: 'dea-guadeloupe-01',
    typeId: 'dea',
    nom: "Direction de l'environnement de l'aménagement et du logement (DEAL) - Guadeloupe",
    abreviation: 'DEAL - Guadeloupe',
    url: 'http://www.guadeloupe.developpement-durable.gouv.fr',
    email: 'deal-guadeloupe@developpement-durable.gouv.fr',
    telephone: '+33 (0)5 90 99 46 46',
    adresse1: 'Route de St Phy\n97102 Basse-Terre',
    adresse2: 'Adresse postale\r\nDEAL Guadeloupe\nBP 54\n97102 Basse-Terre',
    codePostal: '97102',
    commune: 'Basse-Terre',
    cedex: 'Cedex',
    regionId: '01'
  },
  'dea-guyane-01': {
    id: 'dea-guyane-01',
    typeId: 'dea',
    nom: 'Direction Générale des Territoires et de la Mer de Guyane',
    abreviation: 'DGTM - Guyane',
    url: 'http://www.guyane.developpement-durable.gouv.fr',
    telephone: '+594 5 94 39 80 00',
    adresse1: 'Route du Vieux-Port\n97300 Cayenne',
    adresse2: 'Adresse postale\nRoute du Vieux-Port\nCS 76003\n97306 Cayenne',
    codePostal: '97300',
    commune: 'Cayenne',
    cedex: 'Cedex',
    regionId: '03'
  },
  'dea-martinique-01': {
    id: 'dea-martinique-01',
    typeId: 'dea',
    nom: "Direction de l'environnement de l'aménagement et du logement (DEAL) - Martinique",
    abreviation: 'DEAL - Martinique',
    url: 'http://www.martinique.developpement-durable.gouv.fr',
    email: 'deal-martinique-usagers@developpement-durable.gouv.fr',
    telephone: '+33 (0)5 96 59 57 00',
    adresse1: 'B.P. 7212\n97274 Schœlcher',
    codePostal: '97274',
    commune: 'Schœlcher',
    cedex: 'Cedex',
    regionId: '02'
  },
  'dea-mayotte-01': {
    id: 'dea-mayotte-01',
    typeId: 'dea',
    nom: "Direction de l'environnement de l'aménagement et du logement (DEAL) - Mayotte",
    abreviation: 'DEAL - Mayotte',
    url: 'http://www.mayotte.gouv.fr/Services-de-l-Etat/Direction-de-l-Environnement-de-l-Amenagement-et-du-Logement-DEAL',
    email: 'de-mayotte@equipement.gouv.fr',
    telephone: '+262 269 61 12 54',
    adresse1: "Terre plein de M'Tsapéré\n97600 Mamoudzou",
    adresse2: 'Adresse postale\nBP 109\n97600 Mamoudzou',
    codePostal: '97600',
    commune: 'Mamoudzou',
    cedex: 'Cedex',
    regionId: '06'
  },
  'dea-reunion-01': {
    id: 'dea-reunion-01',
    typeId: 'dea',
    nom: "Direction de l'environnement de l'aménagement et du logement (DEAL) - La Réunion",
    abreviation: 'DEAL - La Réunion',
    url: 'http://www.reunion.developpement-durable.gouv.fr',
    email: 'deal-reunion@developpement-durable.gouv.fr',
    telephone: '+33 (0)2 62 40 26 26',
    adresse1: '2 rue Juliette Dodu\nCS 41009\r\n97743 Saint-Denis',
    codePostal: '97743',
    commune: 'Saint-Denis',
    cedex: 'Cedex',
    regionId: '04'
  },
  'dre-aura-01': {
    id: 'dre-aura-01',
    typeId: 'dre',
    nom: "Direction régionale de l'environnement, de l'aménagement et du logement (DREAL) - Auvergne-Rhône-Alpes - Siège de Lyon",
    abreviation: 'DREAL - Auvergne-Rhône-Alpes - Siège de Lyon',
    url: 'http://www.auvergne-rhone-alpes.developpement-durable.gouv.fr',
    email: 'dir.dreal-auvergne-rhone-alpes@developpement-durable.gouv.fr',
    telephone: '+33 (0)4 26 28 60 00',
    adresse1: '5 place Jules-Ferry\n69006 Lyon',
    adresse2: 'Adresse postale\nDreal Rhône-Alpes\n69453 Lyon Cedex 6',
    codePostal: '69006',
    commune: 'Lyon',
    cedex: 'Cedex',
    regionId: '84'
  },
  'dre-bfc-01': {
    id: 'dre-bfc-01',
    typeId: 'dre',
    nom: "Direction régionale de l'environnement, de l'aménagement et du logement (DREAL) - Bourgogne-Franche-Comté - Siège de Besançon",
    abreviation: 'DREAL - Bourgogne-Franche-Comté - Siège de Besançon',
    url: 'http://www.bourgogne-franche-comte.developpement-durable.gouv.fr',
    telephone: '+33 (0)3 39 59 62 00',
    adresse1: '5 voie Gisèle Halimi',
    adresse2: 'BP 31269 ',
    codePostal: '25005',
    commune: 'Besançon',
    cedex: 'Cedex',
    regionId: '27'
  },
  'dre-bretagne-01': {
    id: 'dre-bretagne-01',
    typeId: 'dre',
    nom: "Direction régionale de l'environnement, de l'aménagement et du logement (DREAL) - Bretagne",
    abreviation: 'DREAL - Bretagne',
    url: 'http://www.bretagne.developpement-durable.gouv.fr',
    email: 'dreal-bretagne@developpement-durable.gouv.fr',
    telephone: '+33 (0)2 99 33 45 55',
    adresse1: '10 rue Maurice-Fabre\nCS 96515\n35065 Rennes',
    codePostal: '35065',
    commune: 'Rennes',
    cedex: 'Cedex',
    regionId: '53'
  },
  'dre-centre-val-de-loire-01': {
    id: 'dre-centre-val-de-loire-01',
    typeId: 'dre',
    nom: "Direction régionale de l'environnement, de l'aménagement et du logement (DREAL) - Centre-Val-de-Loire",
    abreviation: 'DREAL - Centre-Val-de-Loire',
    url: 'http://www.centre.developpement-durable.gouv.fr',
    email: 'dreal-centre@developpement-durable.gouv.fr',
    telephone: '+33 (0)2 36 17 41 41',
    adresse1: '5 avenue Buffon\nCS 96407\n45064 Orléans',
    codePostal: '45064',
    commune: 'Orléans',
    cedex: 'Cedex',
    regionId: '24'
  },
  'dre-corse-01': {
    id: 'dre-corse-01',
    typeId: 'dre',
    nom: "Direction régionale de l'environnement, de l'aménagement et du logement (DREAL) - Corse",
    abreviation: 'DREAL - Corse',
    url: 'http://www.corse.developpement-durable.gouv.fr',
    email: 'dreal-corse@developpement-durable.gouv.fr',
    telephone: '+33 (0)4 95 51 79 70',
    adresse1: '19 cours Napoléon\nBâtiment D\nCS 10006\n20704 Ajaccio',
    codePostal: '20704',
    commune: 'Ajaccio',
    cedex: 'Cedex',
    regionId: '94'
  },
  'dre-grand-est-01': {
    id: 'dre-grand-est-01',
    typeId: 'dre',
    nom: "Direction régionale de l'environnement, de l'aménagement et du logement (DREAL) - Grand Est - Siège de Metz",
    abreviation: 'DREAL - Grand Est - Siège de Metz',
    url: 'http://www.grand-est.developpement-durable.gouv.fr',
    telephone: '+33 (0)3 87 62 81 00',
    adresse1: 'Greenpark\n2 rue Augustin-Fresnel\nBP 95038\n57071 Metz',
    codePostal: '57071',
    commune: 'Metz',
    cedex: 'Cedex',
    regionId: '44'
  },
  'dre-hauts-de-france-01': {
    id: 'dre-hauts-de-france-01',
    typeId: 'dre',
    nom: "Direction régionale de l'environnement, de l'aménagement et du logement (DREAL) - Hauts-de-France - Siège de Lille",
    abreviation: 'DREAL - Hauts-de-France - Siège de Lille',
    url: 'http://www.hauts-de-france.developpement-durable.gouv.fr',
    telephone: '+33 (0)3 20 13 48 48',
    adresse1: '44 rue de Tournai\nCS 40259\n59019 Lille',
    codePostal: '59019',
    commune: 'Lille',
    cedex: 'Cedex',
    regionId: '32'
  },
  'dre-ile-de-france-01': {
    id: 'dre-ile-de-france-01',
    typeId: 'dre',
    nom: "Direction régionale et interdépartementale de l'environnement et de l'énergie (DRIEE) - Île-de-France",
    abreviation: 'DRIEE - Île-de-France',
    url: 'http://www.driee.ile-de-france.developpement-durable.gouv.fr',
    email: 'driee-if@developpement-durable.gouv.fr',
    telephone: '+33 (0)1 87 36 45 00',
    adresse1: '12 cours Louis Lumière, CS 70027',
    codePostal: '94307',
    commune: 'Vincennes',
    cedex: 'cedex',
    regionId: '11'
  },
  'dre-normandie-01': {
    id: 'dre-normandie-01',
    typeId: 'dre',
    nom: "Direction régionale de l'environnement, de l'aménagement et du logement (DREAL) - Normandie - Siège de Rouen",
    abreviation: 'DREAL - Normandie - Siège de Rouen',
    url: 'http://www.normandie.developpement-durable.gouv.fr',
    email: 'dreal-hnormandie@developpement-durable.gouv.fr',
    telephone: '+33 (0)2 35 58 53 27',
    adresse1: 'BP 86002\nCité administrative\n2 rue Saint-Sever\n76032 Rouen',
    codePostal: '76032',
    commune: 'Rouen',
    cedex: 'Cedex',
    regionId: '28'
  },
  'dre-nouvelle-aquitaine-01': {
    id: 'dre-nouvelle-aquitaine-01',
    typeId: 'dre',
    nom: "Direction régionale de l'environnement, de l'aménagement et du logement (DREAL) - Nouvelle-Aquitaine - Siège de Poitiers",
    abreviation: 'DREAL - Nouvelle-Aquitaine - Siège de Poitiers',
    url: 'http://www.nouvelle-aquitaine.developpement-durable.gouv.fr',
    telephone: '+33 (0)5 49 55 63 63',
    adresse1: '15 rue Arthur-Ranc\nBP 60539\n86020 Poitiers',
    codePostal: '86020',
    commune: 'Poitiers',
    cedex: 'Cedex',
    regionId: '75'
  },
  'dre-occitanie-01': {
    id: 'dre-occitanie-01',
    typeId: 'dre',
    nom: "Direction régionale de l'environnement, de l'aménagement et du logement (DREAL) - Occitanie - Siège de Toulouse",
    abreviation: 'DREAL - Occitanie - Siège de Toulouse',
    url: 'http://www.occitanie.developpement-durable.gouv.fr',
    telephone: '+33 (0)5 61 58 50 00',
    adresse1:
      '1 rue de la Cité-Administrative\nBâtiment G\nCS 80002\n31074 Toulouse',
    codePostal: '31074',
    commune: 'Toulouse',
    cedex: 'Cedex',
    regionId: '76'
  },
  'dre-paca-01': {
    id: 'dre-paca-01',
    typeId: 'dre',
    nom: "Direction régionale de l'environnement, de l'aménagement et du logement (DREAL) - Provence-Alpes-Côte-d'Azur",
    abreviation: "DREAL - Provence-Alpes-Côte-d'Azur",
    url: 'http://www.paca.developpement-durable.gouv.fr',
    telephone: '+33 (0)4 91 28 40 40',
    adresse1: '16 rue Antoine-Zattara\nCS 70248\n13331 Marseille',
    codePostal: '13331',
    commune: 'Marseille',
    cedex: 'Cedex',
    regionId: '93'
  },
  'dre-pays-de-la-loire-01': {
    id: 'dre-pays-de-la-loire-01',
    typeId: 'dre',
    nom: "Direction régionale de l'environnement, de l'aménagement et du logement (DREAL) - Pays de la Loire",
    abreviation: 'DREAL - Pays de la Loire',
    url: 'http://www.pays-de-la-loire.developpement-durable.gouv.fr',
    email: 'dreal-pays-de-la-loire@developpement-durable.gouv.fr',
    telephone: '+33 (0)2 72 74 73 00',
    adresse1: '5 rue Françoise-Giroud\nCS 16326\n44263 Nantes',
    codePostal: '44263',
    commune: 'Nantes',
    cedex: 'Cedex',
    regionId: '52'
  },
  'min-dajb-01': {
    id: 'min-dajb-01',
    typeId: 'min',
    nom: "Ministère de l'Economie, des Finances et de la Relance",
    abreviation: "DAJ - Ministère de l'Economie, des Finances et de la Relance",
    service:
      "Bureau 4C. Droit de l'industrie, de l'énergie et des réseaux de communication",
    url: 'http://www.economie.gouv.fr',
    telephone: '01 44 97 03 32',
    adresse1: '6 rue Louise-Weiss',
    adresse2: 'Télédoc 342',
    codePostal: '75703',
    commune: 'Paris',
    cedex: 'Cedex 13'
  },
  'min-mctrct-dgcl-01': {
    id: 'min-mctrct-dgcl-01',
    typeId: 'min',
    nom: 'Ministère de la Cohésion des Territoires et des Relations avec les Collectivités Territoriales',
    abreviation: 'DGCL/SDFLAE/FL1',
    service: 'Bureau de la fiscalité locale',
    url: 'https://www.cohesion-territoires.gouv.fr/direction-generale-des-collectivites-locales',
    telephone: '01 49 27 31 59',
    adresse1: '2 place des Saussaies',
    codePostal: '75800',
    commune: 'Paris'
  },
  'min-mtes-dgaln-01': {
    id: 'min-mtes-dgaln-01',
    typeId: 'min',
    nom: "Ministère de l'Economie, des Finances et de la Relance & Ministère de la Transition écologique",
    abreviation: 'DGALN/DEB/EARM2',
    service:
      "Bureau de la politique des ressources minérales non énergétiques - Direction générale de l'aménagement, du logement et de la nature (DGALN)",
    url: 'http://www.mineralinfo.fr',
    email: 'earm2.deb.dgaln@developpement-durable.gouv.fr',
    telephone: '+33 (0)1 40 81 21 22',
    adresse1: 'Tour Séquoia',
    adresse2: '1 place Carpeaux',
    codePostal: '92055',
    commune: 'Paris-La-Défense',
    cedex: 'Cedex'
  },
  'min-mtes-dgec-01': {
    id: 'min-mtes-dgec-01',
    typeId: 'min',
    nom: "Ministère de l'Economie, des Finances et de la Relance & Ministère de la Transition écologique",
    abreviation: 'DGEC/DE/SD2/2A',
    service:
      "Bureau Ressources énergétiques du sous-sol (2A) - Direction générale de l'énergie et du climat (DGEC)",
    url: 'http://www.minergies.fr',
    email: '2a.sd2.de.dgec@developpement-durable.gouv.fr',
    telephone: '+33 (0)1 40 81 95 63',
    adresse1: 'Tour Séquoia\n1 place Carpeaux\n92800 Puteaux',
    adresse2: 'Adresse postale\r\n92055 Paris-La-Défense Cedex',
    codePostal: '92800',
    commune: 'Puteaux',
    cedex: 'Cedex'
  },
  'min-mtes-dgpr-01': {
    id: 'min-mtes-dgpr-01',
    typeId: 'min',
    nom: "Ministère de l'Economie, des Finances et de la Relance & Ministère de la Transition écologique",
    abreviation: 'DGPR/SRT/SDRCP/BSSS',
    service:
      'Bureau du sol et du sous-sol - Direction générale de la prévention des risques (DGPR)',
    email: 'bsss.sdrcp.srt.dgpr@developpement-durable.gouv.fr',
    telephone: '+33 (0)1 40 81 21 22',
    adresse1: 'Tour Séquoia\n1 place Carpeaux\n92800 Puteaux',
    adresse2: 'Adresse postale\n92055 Paris-La-Défense Cedex',
    codePostal: '92800',
    commune: 'Puteaux',
    cedex: 'Cedex'
  },
  'ope-brgm-01': {
    id: 'ope-brgm-01',
    typeId: 'ope',
    nom: 'Bureau de recherches géologiques et minières',
    abreviation: 'BRGM',
    url: 'https://www.brgm.fr/',
    telephone: '02 38 64 34 34',
    adresse1: '3 avenue Claude-Guillemin',
    adresse2: 'BP 36009',
    codePostal: '45060',
    commune: 'Orléans',
    cedex: 'Cedex 2'
  },
  'ope-brgm-02': {
    id: 'ope-brgm-02',
    typeId: 'ope',
    nom: 'BRGM - Projet Zercoa',
    abreviation: 'BRGM - Projet Zercoa',
    service:
      'BRGM - Equipe projet "zones favorables à une exploitation et à un réaménagement coordonné de l\'or alluvionnaire"',
    url: 'https://www.brgm.fr//',
    telephone: '02 38 64 34 34',
    adresse1: '3 avenue Claude-Guillemin',
    adresse2: 'BP 36009',
    codePostal: '45060',
    commune: 'Orléans',
    cedex: 'Cedex 2'
  },
  'ope-cacem-01': {
    id: 'ope-cacem-01',
    typeId: 'ope',
    nom: "Centre d'appui au contrôle de l'environnement marin",
    abreviation: 'Cacem',
    service: 'DIRM NAMO/DOSM/CROSS Etel/CACEM',
    url: 'http://extranet.legicem.metier.developpement-durable.gouv.fr',
    email: 'cacem@developpement-durable.gouv.fr',
    adresse1:
      'Centre régional opérationnel de surveillance et de sauvetage Atlantique',
    adresse2: '40 avenue L. Bougo',
    codePostal: '56410',
    commune: 'Etel'
  },
  'ope-onf-973-01': {
    id: 'ope-onf-973-01',
    typeId: 'ope',
    nom: 'Office national des forêts',
    abreviation: 'Office national des forêts',
    service: 'Direction territoriale Guyane',
    url: 'http://www1.onf.fr/guyane/@@index.html',
    email: 'pole.minier@onf.fr',
    telephone: '+594 (0)5 94 25 53 78',
    adresse1: '541 route de Montabo',
    adresse2: 'Adresse postale\r\n541 route de Montabo\nCS87002',
    codePostal: '97300',
    commune: 'Cayenne',
    regionId: '03'
  },
  'ope-ptmg-973-01': {
    id: 'ope-ptmg-973-01',
    typeId: 'ope',
    nom: 'Pôle Technique Minier de Guyane',
    abreviation: 'Pôle Technique Minier de Guyane',
    telephone: '+594 (0)5 94 30 06 00',
    adresse1:
      'Hôtel de la Collectivité Territoriale de Guyane, Carrefour de Suzini',
    adresse2: '4179 route de Montabo',
    codePostal: '97307',
    commune: 'Cayenne'
  },
  'pre-01053-01': {
    id: 'pre-01053-01',
    typeId: 'pre',
    nom: 'Préfecture - Ain',
    abreviation: 'Préfecture - Ain',
    url: 'http://www.ain.gouv.fr',
    email: 'prefecture@ain.gouv.fr',
    telephone: '04 74 32 30 00',
    adresse1: "45, avenue d'Alsace-Lorraine, CS 80400, Quartier Bourg centre",
    codePostal: '01012',
    commune: 'Bourg-en-Bresse Cedex',
    cedex: 'Cedex',
    departementId: '01'
  },
  'pre-02408-01': {
    id: 'pre-02408-01',
    typeId: 'pre',
    nom: 'Préfecture - Aisne',
    abreviation: 'Préfecture - Aisne',
    url: 'http://www.aisne.gouv.fr',
    email: 'prefecture@aisne.gouv.fr',
    telephone: '03 23 21 82 82',
    adresse1: '2, rue Paul-Doumer',
    codePostal: '02010',
    commune: 'Laon Cedex',
    cedex: 'Cedex',
    departementId: '02'
  },
  'pre-03190-01': {
    id: 'pre-03190-01',
    typeId: 'pre',
    nom: 'Préfecture - Allier',
    abreviation: 'Préfecture - Allier',
    url: 'http://www.allier.gouv.fr',
    email: 'prefecture@allier.gouv.fr',
    telephone: '04 70 48 30 00',
    adresse1: "2, rue Michel-de-L'Hospital, CS 31649",
    codePostal: '03016',
    commune: 'Moulins Cedex',
    cedex: 'Cedex',
    departementId: '03'
  },
  'pre-04070-01': {
    id: 'pre-04070-01',
    typeId: 'pre',
    nom: 'Préfecture - Alpes-de-Haute-Provence',
    abreviation: 'Préfecture - Alpes-de-Haute-Provence',
    url: 'http://www.alpes-de-haute-provence.gouv.fr',
    telephone: '04 92 36 72 00',
    adresse1: '8, rue Docteur-Romieu',
    codePostal: '04016',
    commune: 'Digne-les-Bains Cedex',
    cedex: 'Cedex',
    departementId: '04'
  },
  'pre-05061-01': {
    id: 'pre-05061-01',
    typeId: 'pre',
    nom: 'Préfecture - Hautes-Alpes',
    abreviation: 'Préfecture - Hautes-Alpes',
    url: 'http://www.hautes-alpes.gouv.fr',
    email: 'prefecture@hautes-alpes.gouv.fr',
    telephone: '04 92 40 48 00',
    adresse1: '28, rue Saint-Arey, CS 66002',
    codePostal: '05011',
    commune: 'Gap Cedex',
    cedex: 'Cedex',
    departementId: '05'
  },
  'pre-06088-01': {
    id: 'pre-06088-01',
    typeId: 'pre',
    nom: 'Préfecture - Alpes-Maritimes',
    abreviation: 'Préfecture - Alpes-Maritimes',
    url: 'http://www.alpes-maritimes.gouv.fr',
    telephone: '04 93 72 20 00',
    adresse1: 'CADAM, 147, route de Grenoble',
    adresse2:
      "Services de l'État dans les Alpes-Maritimes, Préfecture, CADAM, 147, route de Grenoble",
    codePostal: '06000',
    commune: 'Nice',
    departementId: '06'
  },
  'pre-07186-01': {
    id: 'pre-07186-01',
    typeId: 'pre',
    nom: 'Préfecture - Ardèche',
    abreviation: 'Préfecture - Ardèche',
    url: 'http://www.ardeche.gouv.fr',
    email: 'pref-courrier@ardeche.gouv.fr',
    telephone: '04 75 66 50 00',
    adresse1: '4, boulevard de Vernon',
    codePostal: '07000',
    commune: 'Privas',
    departementId: '07'
  },
  'pre-08105-01': {
    id: 'pre-08105-01',
    typeId: 'pre',
    nom: 'Préfecture - Ardennes',
    abreviation: 'Préfecture - Ardennes',
    url: 'http://www.ardennes.gouv.fr',
    email: 'prefecture@ardennes.gouv.fr',
    telephone: '03 24 59 66 00',
    adresse1: '1, place de la Préfecture, BP 60002',
    codePostal: '08005',
    commune: 'Charleville-Mézières Cedex',
    cedex: 'Cedex',
    departementId: '08'
  },
  'pre-09122-01': {
    id: 'pre-09122-01',
    typeId: 'pre',
    nom: 'Préfecture - Ariège',
    abreviation: 'Préfecture - Ariège',
    url: 'http://www.ariege.gouv.fr',
    email: 'prefecture@ariege.gouv.fr',
    telephone: '05 61 02 10 00',
    adresse1: '2, rue de la Préfecture - Préfet Claude Erignac, BP 4087',
    codePostal: '09007',
    commune: 'Foix Cedex',
    cedex: 'Cedex',
    departementId: '09'
  },
  'pre-10387-01': {
    id: 'pre-10387-01',
    typeId: 'pre',
    nom: 'Préfecture - Aube',
    abreviation: 'Préfecture - Aube',
    url: 'http://www.aube.gouv.fr',
    email: 'prefecture@aube.gouv.fr',
    telephone: '03 25 42 35 00',
    adresse1: 'CS 20372, 2, rue Pierre-Labonde',
    codePostal: '10025',
    commune: 'Troyes Cedex',
    cedex: 'Cedex',
    departementId: '10'
  },
  'pre-11069-01': {
    id: 'pre-11069-01',
    typeId: 'pre',
    nom: 'Préfecture - Aude',
    abreviation: 'Préfecture - Aude',
    url: 'http://www.aude.gouv.fr',
    email: 'prefecture@aude.gouv.fr',
    telephone: '04 68 10 27 00',
    adresse1: 'CS 20001, 52, rue Jean-Bringer',
    codePostal: '11836',
    commune: 'Carcassonne Cedex 9',
    cedex: 'Cedex 9',
    departementId: '11'
  },
  'pre-12202-01': {
    id: 'pre-12202-01',
    typeId: 'pre',
    nom: 'Préfecture - Aveyron',
    abreviation: 'Préfecture - Aveyron',
    url: 'http://www.aveyron.gouv.fr',
    email: 'prefecture@aveyron.fr',
    telephone: '05 65 75 71 71',
    adresse1: 'Centre administratif Foch, Place Foch',
    codePostal: '12000',
    commune: 'Rodez',
    cedex: 'Cedex',
    departementId: '12'
  },
  'pre-13203-01': {
    id: 'pre-13203-01',
    typeId: 'pre',
    nom: 'Préfecture - Bouches-du-Rhône',
    abreviation: 'Préfecture - Bouches-du-Rhône',
    url: 'http://www.bouches-du-rhone.gouv.fr',
    email: 'contact@bouches-du-rhone.pref.gouv.fr',
    telephone: '04 84 35 40 00',
    adresse1: 'Boulevard Paul-Peytral',
    codePostal: '13282',
    commune: 'Marseille Cedex 20',
    cedex: 'Cedex 20',
    departementId: '13'
  },
  'pre-14118-01': {
    id: 'pre-14118-01',
    typeId: 'pre',
    nom: 'Préfecture - Calvados',
    abreviation: 'Préfecture - Calvados',
    url: 'http://www.calvados.gouv.fr',
    email: 'prefecture@calvados.gouv.fr',
    telephone: '02 31 30 64 00',
    adresse1: 'Rue Daniel-Huet',
    codePostal: '14038',
    commune: 'Caen Cedex 9',
    cedex: 'Cedex 9',
    departementId: '14'
  },
  'pre-15014-01': {
    id: 'pre-15014-01',
    typeId: 'pre',
    nom: 'Préfecture - Cantal',
    abreviation: 'Préfecture - Cantal',
    url: 'http://www.cantal.gouv.fr',
    email: 'courrier@cantal.pref.gouv.fr',
    telephone: '04 71 46 23 00',
    adresse1: 'Cours Monthyon, BP 529',
    codePostal: '15005',
    commune: 'Aurillac Cedex',
    cedex: 'Cedex',
    departementId: '15'
  },
  'pre-16015-01': {
    id: 'pre-16015-01',
    typeId: 'pre',
    nom: 'Préfecture - Charente',
    abreviation: 'Préfecture - Charente',
    url: 'http://www.charente.gouv.fr',
    email: 'communication@charente.gouv.fr',
    telephone: '05 45 97 61 00',
    adresse1: '7-9, rue de la Préfecture, CS 92301',
    codePostal: '16023',
    commune: 'Angoulême Cedex',
    cedex: 'Cedex',
    departementId: '16'
  },
  'pre-17300-01': {
    id: 'pre-17300-01',
    typeId: 'pre',
    nom: 'Préfecture - Charente-Maritime',
    abreviation: 'Préfecture - Charente-Maritime',
    url: 'http://www.charente-maritime.gouv.fr',
    email: 'prefecture@charente-maritime.gouv.fr',
    telephone: '05 46 27 43 00',
    adresse1: 'CS 70000, 38, rue Réaumur',
    codePostal: '17017',
    commune: 'La Rochelle Cedex 1',
    cedex: 'Cedex 1',
    departementId: '17'
  },
  'pre-18033-01': {
    id: 'pre-18033-01',
    typeId: 'pre',
    nom: 'Préfecture - Cher',
    abreviation: 'Préfecture - Cher',
    url: 'http://www.cher.gouv.fr',
    email: 'prefecture@cher.gouv.fr',
    telephone: '02 48 67 18 18',
    adresse1: 'Place Marcel-Plaisant, CS 60022',
    codePostal: '18020',
    commune: 'Bourges Cedex',
    cedex: 'Cedex',
    departementId: '18'
  },
  'pre-19272-01': {
    id: 'pre-19272-01',
    typeId: 'pre',
    nom: 'Préfecture - Corrèze',
    abreviation: 'Préfecture - Corrèze',
    url: 'http://www.correze.gouv.fr',
    email: 'prefecture@correze.gouv.fr',
    telephone: '05 55 20 55 20',
    adresse1: '1, rue Souham, BP 250',
    codePostal: '19012',
    commune: 'Tulle Cedex',
    cedex: 'Cedex',
    departementId: '19'
  },
  'pre-21231-01': {
    id: 'pre-21231-01',
    typeId: 'pre',
    nom: "Préfecture - Côte-d'Or",
    abreviation: "Préfecture - Côte-d'Or",
    url: 'http://www.cote-dor.gouv.fr',
    telephone: '03 80 44 64 00',
    adresse1: '53, rue de la Préfecture',
    codePostal: '21041',
    commune: 'Dijon Cedex',
    cedex: 'Cedex',
    departementId: '21'
  },
  'pre-22278-01': {
    id: 'pre-22278-01',
    typeId: 'pre',
    nom: "Préfecture - Côtes-d'Armor",
    abreviation: "Préfecture - Côtes-d'Armor",
    url: 'http://www.cotes-darmor.gouv.fr',
    email: 'prefecture@cotes-darmor.gouv.fr',
    telephone: '02 96 62 44 22',
    adresse1: '1, place du Général-de-Gaulle, BP 2370',
    codePostal: '22023',
    commune: 'Saint-Brieuc Cedex 1',
    cedex: 'Cedex 1',
    departementId: '22'
  },
  'pre-23096-01': {
    id: 'pre-23096-01',
    typeId: 'pre',
    nom: 'Préfecture - Creuse',
    abreviation: 'Préfecture - Creuse',
    url: 'http://www.creuse.gouv.fr',
    telephone: '05 55 51 59 00',
    adresse1: 'BP 79, Place Louis-Lacrocq',
    codePostal: '23011',
    commune: 'Guéret Cedex',
    cedex: 'Cedex',
    departementId: '23'
  },
  'pre-24322-01': {
    id: 'pre-24322-01',
    typeId: 'pre',
    nom: 'Préfecture - Dordogne',
    abreviation: 'Préfecture - Dordogne',
    url: 'http://www.dordogne.gouv.fr',
    email: 'prefecture@dordogne.gouv.fr',
    telephone: '05 53 02 24 24',
    adresse1: '2, rue Paul-Louis-Courier',
    adresse2:
      "Services de l'État - Préfecture de la Dordogne, Cité adminsitrative",
    codePostal: '24000',
    commune: 'Périgueux',
    departementId: '24'
  },
  'pre-25056-01': {
    id: 'pre-25056-01',
    typeId: 'pre',
    nom: 'Préfecture - Doubs',
    abreviation: 'Préfecture - Doubs',
    url: 'http://www.doubs.gouv.fr',
    email: 'pref-courrier@doubs.gouv.fr',
    telephone: '03 81 25 10 00',
    adresse1: '8 bis, rue Charles-Nodier',
    codePostal: '25035',
    commune: 'Besançon Cedex',
    departementId: '25'
  },
  'pre-26362-01': {
    id: 'pre-26362-01',
    typeId: 'pre',
    nom: 'Préfecture - Drôme',
    abreviation: 'Préfecture - Drôme',
    url: 'http://www.drome.gouv.fr',
    email: 'prefecture@drome.gouv.fr',
    telephone: '04 75 79 28 00',
    adresse1: '3, boulevard Vauban',
    codePostal: '26030',
    commune: 'Valence Cedex 9',
    departementId: '26'
  },
  'pre-27229-01': {
    id: 'pre-27229-01',
    typeId: 'pre',
    nom: 'Préfecture - Eure',
    abreviation: 'Préfecture - Eure',
    url: 'http://www.seine-maritime.gouv.fr/Outils/Horaires-et-coordonnees/Prefecture-de-l-Eure',
    email: 'courrier-web@eure.gouv.fr',
    telephone: '02 32 78 27 27',
    adresse1: 'Boulevard Georges-Chauvin',
    codePostal: '27022',
    commune: 'Evreux Cedex',
    departementId: '27'
  },
  'pre-28085-01': {
    id: 'pre-28085-01',
    typeId: 'pre',
    nom: 'Préfecture - Eure-et-Loir',
    abreviation: 'Préfecture - Eure-et-Loir',
    url: 'http://www.eure-et-loir.gouv.fr',
    telephone: '02 37 27 72 00',
    adresse1: 'Place de la République, CS 80537',
    codePostal: '28019',
    commune: 'Chartres Cedex',
    departementId: '28'
  },
  'pre-29232-01': {
    id: 'pre-29232-01',
    typeId: 'pre',
    nom: 'Préfecture - Finistère',
    abreviation: 'Préfecture - Finistère',
    url: 'http://www.finistere.gouv.fr',
    email: 'prefecture@finistere.gouv.fr',
    telephone: '02 98 76 29 29',
    adresse1: '42, boulevard Dupleix',
    codePostal: '29320',
    commune: 'Quimper Cedex',
    cedex: 'Cedex',
    departementId: '29'
  },
  'pre-2A004-01': {
    id: 'pre-2A004-01',
    typeId: 'pre',
    nom: 'Préfecture - Corse-du-Sud',
    abreviation: 'Préfecture - Corse-du-Sud',
    url: 'http://www.corse-du-sud.gouv.fr',
    email: 'prefecture@corse-du-sud.gouv.fr',
    telephone: '04 95 11 12 13',
    adresse1: 'Palais Lantivy, Cours Napoléon',
    codePostal: '20188',
    commune: 'Ajaccio Cedex 9',
    cedex: 'Cedex 9',
    departementId: '2A'
  },
  'pre-2B033-01': {
    id: 'pre-2B033-01',
    typeId: 'pre',
    nom: 'Préfecture - Haute-Corse',
    abreviation: 'Préfecture - Haute-Corse',
    url: 'http://www.haute-corse.gouv.fr',
    email: 'prefecture.haute-corse@haute-corse.pref.gouv.fr',
    telephone: '04 95 34 50 00',
    adresse1: 'CS 60007, Rond-Point du Maréchal-Leclerc-de-Hautecloque',
    codePostal: '20401',
    commune: 'Bastia Cedex 09',
    departementId: '2B'
  },
  'pre-30189-01': {
    id: 'pre-30189-01',
    typeId: 'pre',
    nom: 'Préfecture - Gard',
    abreviation: 'Préfecture - Gard',
    url: 'http://www.gard.gouv.fr',
    email: 'prefecture@gard.gouv.fr',
    telephone: '0820 09 11 72',
    adresse1: '2, rue Guillemette, 19, avenue Feuchères (étrangers)',
    adresse2: '10, avenue Feuchères',
    codePostal: '30000',
    commune: 'Nîmes',
    departementId: '30'
  },
  'pre-31555-01': {
    id: 'pre-31555-01',
    typeId: 'pre',
    nom: 'Préfecture - Haute-Garonne',
    abreviation: 'Préfecture - Haute-Garonne',
    url: 'http://www.haute-garonne.gouv.fr',
    telephone: '05 34 45 34 45',
    adresse1: '1 place Saint-Étienne',
    adresse2: 'Place Saint-Étienne',
    codePostal: '31000',
    commune: 'Toulouse',
    departementId: '31'
  },
  'pre-32013-01': {
    id: 'pre-32013-01',
    typeId: 'pre',
    nom: 'Préfecture - Gers',
    abreviation: 'Préfecture - Gers',
    url: 'http://www.gers.gouv.fr',
    email: 'prefecture@gers.gouv.fr',
    telephone: '05 62 61 44 00',
    adresse1: '3, place du Préfet Claude-Erignac',
    codePostal: '32007',
    commune: 'Auch Cedex',
    departementId: '32'
  },
  'pre-33063-01': {
    id: 'pre-33063-01',
    typeId: 'pre',
    nom: 'Préfecture - Gironde',
    abreviation: 'Préfecture - Gironde',
    url: 'http://www.gironde.gouv.fr',
    telephone: '05 56 90 60 60',
    adresse1: 'Rue Claude-Bonnier',
    adresse2: '2, esplanade Charles-de-Gaulle, CS 41397',
    codePostal: '33000',
    commune: 'Bordeaux',
    departementId: '33'
  },
  'pre-34172-01': {
    id: 'pre-34172-01',
    typeId: 'pre',
    nom: 'Préfecture - Hérault',
    abreviation: 'Préfecture - Hérault',
    url: 'http://www.herault.gouv.fr',
    telephone: '04 67 61 61 61',
    adresse1: '34, place des Martyrs-de-la-Résistance',
    codePostal: '34062',
    commune: 'Montpellier Cedex 2',
    cedex: 'Cedex 2',
    departementId: '34'
  },
  'pre-35238-01': {
    id: 'pre-35238-01',
    typeId: 'pre',
    nom: 'Préfecture - Ille-et-Vilaine',
    abreviation: 'Préfecture - Ille-et-Vilaine',
    url: 'https://www.ille-et-vilaine.gouv.fr',
    email: 'prefecture@ille-et-vilaine.gouv.fr',
    telephone: '02 99 02 10 35',
    adresse1: '3, avenue de la Préfecture',
    codePostal: '35026',
    commune: 'Rennes Cedex 9',
    departementId: '35'
  },
  'pre-36044-01': {
    id: 'pre-36044-01',
    typeId: 'pre',
    nom: 'Préfecture - Indre',
    abreviation: 'Préfecture - Indre',
    url: 'http://www.indre.gouv.fr',
    telephone: '02 54 29 50 00',
    adresse1: 'Rue des Jeux marins',
    adresse2: 'Place de la Victoire et des Alliés, CS 80583',
    codePostal: '36000',
    commune: 'Châteauroux',
    departementId: '36'
  },
  'pre-37261-01': {
    id: 'pre-37261-01',
    typeId: 'pre',
    nom: 'Préfecture - Indre-et-Loire',
    abreviation: 'Préfecture - Indre-et-Loire',
    url: 'http://www.indre-et-loire.gouv.fr',
    email: 'prefecture@indre-et-loire.gouv.fr',
    telephone: '+ 33 2 47 64 37 37',
    adresse1: '15, rue Bernard-Palissy',
    codePostal: '37925',
    commune: 'Tours Cedex 9',
    cedex: 'Cedex 9',
    departementId: '37'
  },
  'pre-38185-01': {
    id: 'pre-38185-01',
    typeId: 'pre',
    nom: 'Préfecture - Isère',
    abreviation: 'Préfecture - Isère',
    url: 'http://www.isere.gouv.fr',
    telephone: '04 76 60 34 00',
    adresse1: 'CS 71046, Place de Verdun',
    codePostal: '38021',
    commune: 'Grenoble Cedex 1',
    departementId: '38'
  },
  'pre-39300-01': {
    id: 'pre-39300-01',
    typeId: 'pre',
    nom: 'Préfecture - Jura',
    abreviation: 'Préfecture - Jura',
    url: 'http://www.jura.gouv.fr',
    email: 'prefecture@jura.gouv.fr',
    telephone: '03 84 86 84 00',
    adresse1: '8, rue de la Préfecture',
    codePostal: '39030',
    commune: 'Lons-le-Saunier Cedex',
    departementId: '39'
  },
  'pre-40192-01': {
    id: 'pre-40192-01',
    typeId: 'pre',
    nom: 'Préfecture - Landes',
    abreviation: 'Préfecture - Landes',
    url: 'http://www.landes.gouv.fr',
    email: 'prefecture@landes.gouv.fr',
    telephone: '05 58 06 58 06',
    adresse1: '24-26, rue Victor-Hugo',
    codePostal: '40021',
    commune: 'Mont-de-Marsan Cedex',
    departementId: '40'
  },
  'pre-41018-01': {
    id: 'pre-41018-01',
    typeId: 'pre',
    nom: 'Préfecture - Loir-et-Cher',
    abreviation: 'Préfecture - Loir-et-Cher',
    url: 'http://www.loir-et-cher.gouv.fr',
    telephone: '0810 02 41 41',
    adresse1: 'BP 40299, 1, place de la République',
    codePostal: '41006',
    commune: 'Blois Cedex',
    departementId: '41'
  },
  'pre-42218-01': {
    id: 'pre-42218-01',
    typeId: 'pre',
    nom: 'Préfecture - Loire',
    abreviation: 'Préfecture - Loire',
    url: 'http://www.loire.gouv.fr',
    email: 'pref-loire@loire.pref.gouv.fr',
    telephone: '04 77 48 48 48',
    adresse1: '2, rue Charles-de-Gaulle',
    codePostal: '42022',
    commune: 'Saint-Etienne Cedex 1',
    departementId: '42'
  },
  'pre-43157-01': {
    id: 'pre-43157-01',
    typeId: 'pre',
    nom: 'Préfecture - Haute-Loire',
    abreviation: 'Préfecture - Haute-Loire',
    url: 'http://www.haute-loire.gouv.fr',
    email: 'prefecture@haute-loire.gouv.fr',
    telephone: '04 71 09 43 43',
    adresse1: '6, avenue du Général-de-Gaulle, CS 40321',
    codePostal: '43009',
    commune: 'Le Puy-en-Velay Cedex',
    cedex: 'Cedex',
    departementId: '43'
  },
  'pre-44109-01': {
    id: 'pre-44109-01',
    typeId: 'pre',
    nom: 'Préfecture - Loire-Atlantique',
    abreviation: 'Préfecture - Loire-Atlantique',
    url: 'http://www.loire-atlantique.gouv.fr',
    telephone: '02 40 41 20 20',
    adresse1: '6, quai Ceineray, BP 33515',
    codePostal: '44035',
    commune: 'Nantes Cedex 1',
    departementId: '44'
  },
  'pre-45234-01': {
    id: 'pre-45234-01',
    typeId: 'pre',
    nom: 'Préfecture - Loiret',
    abreviation: 'Préfecture - Loiret',
    url: 'http://www.loiret.gouv.fr',
    telephone: '0821 80 30 45',
    adresse1: '181, rue de Bourgogne',
    codePostal: '45042',
    commune: 'Orléans Cedex 1',
    departementId: '45'
  },
  'pre-46042-01': {
    id: 'pre-46042-01',
    typeId: 'pre',
    nom: 'Préfecture - Lot',
    abreviation: 'Préfecture - Lot',
    url: 'http://www.lot.gouv.fr',
    email: 'prefecture@lot.gouv.fr',
    telephone: '05 65 23 10 00',
    adresse1: 'Cité Bessières',
    codePostal: '46009',
    commune: 'Cahors Cedex 9',
    departementId: '46'
  },
  'pre-47001-01': {
    id: 'pre-47001-01',
    typeId: 'pre',
    nom: 'Préfecture - Lot-et-Garonne',
    abreviation: 'Préfecture - Lot-et-Garonne',
    url: 'http://www.lot-et-garonne.gouv.fr',
    telephone: '05 53 77 60 47',
    adresse1: 'Place de Verdun',
    codePostal: '47920',
    commune: 'Agen Cedex 9',
    departementId: '47'
  },
  'pre-48095-01': {
    id: 'pre-48095-01',
    typeId: 'pre',
    nom: 'Préfecture - Lozère',
    abreviation: 'Préfecture - Lozère',
    url: 'http://www.lozere.gouv.fr',
    email: 'prefecture@lozere.gouv.fr',
    telephone: '04 66 49 60 00',
    adresse1: 'Rue du Faubourg-Montbel',
    adresse2: 'BP 130',
    codePostal: '48000',
    commune: 'Mende',
    departementId: '48'
  },
  'pre-49007-01': {
    id: 'pre-49007-01',
    typeId: 'pre',
    nom: 'Préfecture - Maine-et-Loire',
    abreviation: 'Préfecture - Maine-et-Loire',
    url: 'http://www.maine-et-loire.gouv.fr',
    email: 'modernisation@maine-et-loire.pref.gouv.fr',
    telephone: '02 41 81 81 81',
    adresse1: 'Place Michel-Debré',
    codePostal: '49934',
    commune: 'Angers Cedex 9',
    departementId: '49'
  },
  'pre-50502-01': {
    id: 'pre-50502-01',
    typeId: 'pre',
    nom: 'Préfecture - Manche',
    abreviation: 'Préfecture - Manche',
    url: 'http://www.manche.gouv.fr',
    email: 'prefecture@manche.gouv.fr',
    telephone: '02 33 75 49 50',
    adresse1: 'Place de la Préfecture, BP 70522',
    codePostal: '50002',
    commune: 'Saint-Lô Cedex',
    departementId: '50'
  },
  'pre-51108-01': {
    id: 'pre-51108-01',
    typeId: 'pre',
    nom: 'Préfecture - Marne',
    abreviation: 'Préfecture - Marne',
    url: 'http://www.marne.gouv.fr',
    email: 'contact@marne.gouv.fr',
    telephone: '03 26 26 10 10',
    adresse1: '38, rue Carnot',
    codePostal: '51036',
    commune: 'Châlons-en-Champagne Cedex',
    departementId: '51'
  },
  'pre-52121-01': {
    id: 'pre-52121-01',
    typeId: 'pre',
    nom: 'Préfecture - Haute-Marne',
    abreviation: 'Préfecture - Haute-Marne',
    url: 'http://www.haute-marne.gouv.fr',
    email: 'prefecture@haute-marne.gouv.fr',
    telephone: '03 25 30 52 52',
    adresse1: '89, rue de la Victoire-de-la-Marne',
    codePostal: '52011',
    commune: 'Chaumont Cedex',
    departementId: '52'
  },
  'pre-53130-01': {
    id: 'pre-53130-01',
    typeId: 'pre',
    nom: 'Préfecture - Mayenne',
    abreviation: 'Préfecture - Mayenne',
    url: 'http://www.mayenne.gouv.fr',
    email: 'pref-communication@mayenne.gouv.fr',
    telephone: '02 43 01 50 00',
    adresse1: '46, rue Mazagran, CS 91507',
    codePostal: '53015',
    commune: 'Laval Cedex',
    departementId: '53'
  },
  'pre-54395-01': {
    id: 'pre-54395-01',
    typeId: 'pre',
    nom: 'Préfecture - Meurthe-et-Moselle',
    abreviation: 'Préfecture - Meurthe-et-Moselle',
    url: 'http://www.meurthe-et-moselle.gouv.fr',
    email: 'pref-informations@meurthe-et-moselle.gouv.fr',
    telephone: '03 83 34 26 26',
    adresse1: '6, rue Sainte-Catherine',
    adresse2: 'CS 60031, 1, rue du Préfet-Claude-Érignac',
    codePostal: '54000',
    commune: 'Nancy',
    departementId: '54'
  },
  'pre-55029-01': {
    id: 'pre-55029-01',
    typeId: 'pre',
    nom: 'Préfecture - Meuse',
    abreviation: 'Préfecture - Meuse',
    url: 'http://www.meuse.gouv.fr',
    telephone: '03 29 77 55 55',
    adresse1: '40, rue du Bourg, CS 30512',
    codePostal: '55012',
    commune: 'Bar-le-Duc Cedex',
    cedex: 'Cedex',
    departementId: '55'
  },
  'pre-56260-01': {
    id: 'pre-56260-01',
    typeId: 'pre',
    nom: 'Préfecture - Morbihan',
    abreviation: 'Préfecture - Morbihan',
    url: 'http://www.morbihan.gouv.fr',
    telephone: '02 97 54 84 00',
    adresse1: '24, place de la République',
    adresse2: 'Préfecture du Morbihan, BP 501',
    codePostal: '56000',
    commune: 'Vannes',
    departementId: '56'
  },
  'pre-57463-01': {
    id: 'pre-57463-01',
    typeId: 'pre',
    nom: 'Préfecture - Moselle',
    abreviation: 'Préfecture - Moselle',
    telephone: '03 87 34 87 34',
    adresse1: '9, place de la Préfecture, BP 71014',
    codePostal: '57034',
    commune: 'Metz Cedex 01',
    cedex: 'Cedex 01',
    departementId: '57'
  },
  'pre-58194-01': {
    id: 'pre-58194-01',
    typeId: 'pre',
    nom: 'Préfecture - Nièvre',
    abreviation: 'Préfecture - Nièvre',
    url: 'http://www.nievre.gouv.fr',
    email: 'courrier@nievre.pref.gouv.fr',
    telephone: '03 86 60 70 80',
    adresse1: '40, rue de la Préfecture',
    codePostal: '58026',
    commune: 'Nevers Cedex',
    cedex: 'Cedex',
    departementId: '58'
  },
  'pre-59350-01': {
    id: 'pre-59350-01',
    typeId: 'pre',
    nom: 'Préfecture - Nord',
    abreviation: 'Préfecture - Nord',
    url: 'http://www.nord.gouv.fr',
    telephone: '03 20 30 59 59',
    adresse1: 'CS 20003, 12, rue Jean-Sans-Peur',
    codePostal: '59039',
    commune: 'Lille Cedex',
    cedex: 'Cedex',
    departementId: '59'
  },
  'pre-60057-01': {
    id: 'pre-60057-01',
    typeId: 'pre',
    nom: 'Préfecture - Oise',
    abreviation: 'Préfecture - Oise',
    url: 'http://www.oise.gouv.fr',
    telephone: '03 44 06 12 60',
    adresse1: '1, place de la Préfecture',
    codePostal: '60022',
    commune: 'Beauvais Cedex',
    cedex: 'Cedex',
    departementId: '60'
  },
  'pre-61001-01': {
    id: 'pre-61001-01',
    typeId: 'pre',
    nom: 'Préfecture - Orne',
    abreviation: 'Préfecture - Orne',
    url: 'http://www.orne.gouv.fr',
    email: 'pref-communication@orne.gouv.fr',
    telephone: '02 33 80 61 61',
    adresse1: 'BP 529, 39, rue Saint-Blaise',
    codePostal: '61018',
    commune: 'Alençon Cedex',
    cedex: 'Cedex',
    departementId: '61'
  },
  'pre-62041-01': {
    id: 'pre-62041-01',
    typeId: 'pre',
    nom: 'Préfecture - Pas-de-Calais',
    abreviation: 'Préfecture - Pas-de-Calais',
    url: 'http://www.pas-de-calais.gouv.fr',
    telephone: '03 21 21 20 00',
    adresse1: 'Rue Ferdinand-Buisson',
    codePostal: '62020',
    commune: 'Arras Cedex 9',
    cedex: 'Cedex 9',
    departementId: '62'
  },
  'pre-63113-01': {
    id: 'pre-63113-01',
    typeId: 'pre',
    nom: 'Préfecture - Puy-de-Dôme',
    abreviation: 'Préfecture - Puy-de-Dôme',
    url: 'http://www.puy-de-dome.gouv.fr',
    telephone: '04 73 98 63 63',
    adresse1: "1, rue d'Assas",
    codePostal: '63033',
    commune: 'Clermont-Ferrand Cedex 1',
    cedex: 'Cedex 1',
    departementId: '63'
  },
  'pre-64445-01': {
    id: 'pre-64445-01',
    typeId: 'pre',
    nom: 'Préfecture - Pyrénées-Atlantiques',
    abreviation: 'Préfecture - Pyrénées-Atlantiques',
    url: 'http://www.pyrenees-atlantiques.gouv.fr',
    email: 'prefecture@pyrenees-atlantiques.gouv.fr',
    telephone: '05 59 98 24 24',
    adresse1: '2, rue du Maréchal-Joffre',
    codePostal: '64021',
    commune: 'Pau Cedex',
    cedex: 'Cedex',
    departementId: '64'
  },
  'pre-65440-01': {
    id: 'pre-65440-01',
    typeId: 'pre',
    nom: 'Préfecture - Hautes-Pyrénées',
    abreviation: 'Préfecture - Hautes-Pyrénées',
    url: 'http://www.hautes-pyrenees.gouv.fr',
    email: 'prefecture@hautes-pyrenees.gouv.fr',
    telephone: '05 62 56 65 65',
    adresse1: 'CS 61350, Place Charles-de-Gaulle',
    codePostal: '65013',
    commune: 'Tarbes Cedex 9',
    departementId: '65'
  },
  'pre-66136-01': {
    id: 'pre-66136-01',
    typeId: 'pre',
    nom: 'Préfecture - Pyrénées-Orientales',
    abreviation: 'Préfecture - Pyrénées-Orientales',
    url: 'http://www.pyrenees-orientales.gouv.fr',
    telephone: '04 68 51 66 66',
    adresse1: '24, quai Sadi-Carnot, BP 951',
    codePostal: '66951',
    commune: 'Perpignan Cedex',
    cedex: 'Cedex',
    departementId: '66'
  },
  'pre-67482-01': {
    id: 'pre-67482-01',
    typeId: 'pre',
    nom: 'Préfecture - Bas-Rhin',
    abreviation: 'Préfecture - Bas-Rhin',
    url: 'http://www.bas-rhin.gouv.fr',
    telephone: '03 88 21 67 68',
    adresse1: '5 place de la République, BP 1047',
    codePostal: '67073',
    commune: 'Strasbourg Cedex',
    cedex: 'Cedex',
    departementId: '67'
  },
  'pre-68066-01': {
    id: 'pre-68066-01',
    typeId: 'pre',
    nom: 'Préfecture - Haut-Rhin',
    abreviation: 'Préfecture - Haut-Rhin',
    url: 'http://www.haut-rhin.gouv.fr',
    email: 'pref-courrier@haut-rhin.gouv.fr',
    telephone: '03 89 29 20 00',
    adresse1: '11, avenue de la République',
    adresse2: '7, rue Bruat, BP 10489',
    codePostal: '68000',
    commune: 'Colmar',
    departementId: '68'
  },
  'pre-69383-01': {
    id: 'pre-69383-01',
    typeId: 'pre',
    nom: 'Préfecture - Rhône',
    abreviation: 'Préfecture - Rhône',
    url: 'http://www.rhone.gouv.fr',
    telephone: '0821 80 30 69',
    adresse1: '97, rue Molière',
    adresse2: '106, rue Pierre-Corneille',
    codePostal: '69003',
    commune: 'Lyon',
    departementId: '69'
  },
  'pre-70550-01': {
    id: 'pre-70550-01',
    typeId: 'pre',
    nom: 'Préfecture - Haute-Saône',
    abreviation: 'Préfecture - Haute-Saône',
    url: 'http://www.haute-saone.gouv.fr',
    email: 'prefecture@haute-saone.pref.gouv.fr',
    telephone: '03 84 77 70 00',
    adresse1: '1, rue de la Préfecture, BP 429',
    codePostal: '70013',
    commune: 'Vesoul Cedex',
    departementId: '70'
  },
  'pre-71270-01': {
    id: 'pre-71270-01',
    typeId: 'pre',
    nom: 'Préfecture - Saône-et-Loire',
    abreviation: 'Préfecture - Saône-et-Loire',
    url: 'http://www.saone-et-loire.gouv.fr/prefecture-et-sous-prefectures-r1071.html',
    telephone: '03 85 21 81 00',
    adresse1: '196, rue de Strasbourg',
    codePostal: '71021',
    commune: 'Mâcon Cedex 9',
    cedex: 'Cedex 9',
    departementId: '71'
  },
  'pre-72181-01': {
    id: 'pre-72181-01',
    typeId: 'pre',
    nom: 'Préfecture - Sarthe',
    abreviation: 'Préfecture - Sarthe',
    url: 'http://www.sarthe.gouv.fr',
    email: 'pref-mail@sarthe.gouv.fr',
    telephone: '02 43 39 72 72',
    adresse1: 'Place Aristide-Briand',
    codePostal: '72041',
    commune: 'Le Mans Cedex 9',
    cedex: 'Cedex 9',
    departementId: '72'
  },
  'pre-73065-01': {
    id: 'pre-73065-01',
    typeId: 'pre',
    nom: 'Préfecture - Savoie',
    abreviation: 'Préfecture - Savoie',
    url: 'http://www.savoie.gouv.fr',
    email: 'prefecture@savoie.gouv.fr',
    telephone: '04 79 75 50 50',
    adresse1: 'Château des Ducs de Savoie, BP 1801',
    codePostal: '73018',
    commune: 'Chambéry Cedex',
    cedex: 'Cedex',
    departementId: '73'
  },
  'pre-74010-01': {
    id: 'pre-74010-01',
    typeId: 'pre',
    nom: 'Préfecture - Haute-Savoie',
    abreviation: 'Préfecture - Haute-Savoie',
    url: 'http://www.haute-savoie.gouv.fr',
    email: 'prefecture@haute-savoie.gouv.fr',
    telephone: '04 50 33 60 00',
    adresse1: "30, rue du 30e-Régiment-d'Infanterie, BP 2332",
    codePostal: '74034',
    commune: 'Annecy Cedex',
    cedex: 'Cedex',
    departementId: '74'
  },
  'pre-75104-01': {
    id: 'pre-75104-01',
    typeId: 'pre',
    nom: 'Préfecture de police de Paris',
    abreviation: 'Préfecture - Île-de-France',
    url: 'http://www.prefecturedepolice.interieur.gouv.fr',
    telephone: '3430',
    adresse1: '1 bis rue de Lutèce',
    codePostal: '75004',
    commune: 'Paris',
    departementId: '75'
  },
  'pre-76540-01': {
    id: 'pre-76540-01',
    typeId: 'pre',
    nom: 'Préfecture - Seine-Maritime',
    abreviation: 'Préfecture - Seine-Maritime',
    url: 'http://www.seine-maritime.gouv.fr',
    telephone: '02 32 76 50 00',
    adresse1: '7, place de la Madeleine',
    codePostal: '76036',
    commune: 'Rouen Cedex',
    cedex: 'Cedex',
    departementId: '76'
  },
  'pre-77288-01': {
    id: 'pre-77288-01',
    typeId: 'pre',
    nom: 'Préfecture - Seine-et-Marne',
    abreviation: 'Préfecture - Seine-et-Marne',
    url: 'http://www.seine-et-marne.gouv.fr',
    telephone: '01 64 71 76 77',
    adresse1: '12 rue des Saints-Pères',
    codePostal: '77010',
    commune: 'Melun Cedex',
    cedex: 'Cedex',
    departementId: '77'
  },
  'pre-78646-01': {
    id: 'pre-78646-01',
    typeId: 'pre',
    nom: 'Préfecture - Yvelines',
    abreviation: 'Préfecture - Yvelines',
    url: 'http://www.yvelines.gouv.fr',
    email: 'pref-communication78@yvelines.gouv.fr',
    telephone: '01 39 49 78 00',
    adresse1: '1, rue Jean-Houdon',
    codePostal: '78000',
    commune: 'Versailles',
    departementId: '78'
  },
  'pre-79191-01': {
    id: 'pre-79191-01',
    typeId: 'pre',
    nom: 'Préfecture - Deux-Sèvres',
    abreviation: 'Préfecture - Deux-Sèvres',
    url: 'http://www.deux-sevres.gouv.fr',
    email: 'courrier@deux-sevres.pref.gouv.fr',
    telephone: '05 49 08 68 68',
    adresse1: '4, rue Duguesclin, BP 70000',
    codePostal: '79099',
    commune: 'Niort Cedex 9',
    cedex: 'Cedex 9',
    departementId: '79'
  },
  'pre-80021-01': {
    id: 'pre-80021-01',
    typeId: 'pre',
    nom: 'Préfecture - Somme',
    abreviation: 'Préfecture - Somme',
    url: 'http://www.somme.gouv.fr',
    email: 'pref-courrier@somme.gouv.fr',
    telephone: '0821 80 30 80',
    adresse1: '51, rue de la République',
    codePostal: '80020',
    commune: 'Amiens Cedex 9',
    cedex: 'Cedex 9',
    departementId: '80'
  },
  'pre-81004-01': {
    id: 'pre-81004-01',
    typeId: 'pre',
    nom: 'Préfecture - Tarn',
    abreviation: 'Préfecture - Tarn',
    url: 'http://www.tarn.gouv.fr',
    email: 'courrier@tarn.pref.gouv.fr',
    telephone: '05 63 45 61 61',
    adresse1: 'Place de la Préfecture',
    codePostal: '81013',
    commune: 'Albi Cedex 9',
    cedex: 'Cedex 9',
    departementId: '81'
  },
  'pre-82121-01': {
    id: 'pre-82121-01',
    typeId: 'pre',
    nom: 'Préfecture - Tarn-et-Garonne',
    abreviation: 'Préfecture - Tarn-et-Garonne',
    url: 'http://www.tarn-et-garonne.gouv.fr',
    telephone: '05 63 22 82 00',
    adresse1: "2, allée de l'Empereur, BP 779",
    codePostal: '82013',
    commune: 'Montauban Cedex',
    cedex: 'Cedex',
    departementId: '82'
  },
  'pre-83137-01': {
    id: 'pre-83137-01',
    typeId: 'pre',
    nom: 'Préfecture - Var',
    abreviation: 'Préfecture - Var',
    url: 'http://www.var.gouv.fr',
    telephone: '04 94 18 83 83',
    adresse1: "CS 31209, Boulevard du 112e Régiment-d'Infanterie",
    codePostal: '83070',
    commune: 'Toulon Cedex',
    cedex: 'Cedex',
    departementId: '83'
  },
  'pre-84007-01': {
    id: 'pre-84007-01',
    typeId: 'pre',
    nom: 'Préfecture - Vaucluse',
    abreviation: 'Préfecture - Vaucluse',
    url: 'http://www.vaucluse.gouv.fr',
    email: 'pref-contact@vaucluse.gouv.fr',
    telephone: '04 88 17 84 84',
    adresse1: '2, avenue de la Folie',
    adresse2: "Services de l'Etat en Vaucluse Préfecture",
    codePostal: '84000',
    commune: 'Avignon',
    departementId: '84'
  },
  'pre-85191-01': {
    id: 'pre-85191-01',
    typeId: 'pre',
    nom: 'Préfecture - Vendée',
    abreviation: 'Préfecture - Vendée',
    url: 'http://www.vendee.gouv.fr',
    email: 'prefecture@vendee.gouv.fr',
    telephone: '02 51 36 70 85',
    adresse1: '29, rue Delille',
    codePostal: '85922',
    commune: 'La Roche-sur-Yon Cedex 9',
    cedex: 'Cedex 9',
    departementId: '85'
  },
  'pre-86194-01': {
    id: 'pre-86194-01',
    typeId: 'pre',
    nom: 'Préfecture - Vienne',
    abreviation: 'Préfecture - Vienne',
    url: 'http://www.vienne.gouv.fr',
    email: 'pref-courrier@vienne.gouv.fr',
    telephone: '05 49 55 70 00',
    adresse1: 'BP 589, 7, place Aristide-Briand',
    codePostal: '86021',
    commune: 'Poitiers Cedex',
    cedex: 'Cedex',
    departementId: '86'
  },
  'pre-87085-01': {
    id: 'pre-87085-01',
    typeId: 'pre',
    nom: 'Préfecture - Haute-Vienne',
    abreviation: 'Préfecture - Haute-Vienne',
    url: 'http://www.haute-vienne.gouv.fr',
    telephone: '05 55 44 18 00',
    adresse1: '12 rue des Combes',
    codePostal: '87000',
    commune: 'Limoges',
    departementId: '87'
  },
  'pre-88160-01': {
    id: 'pre-88160-01',
    typeId: 'pre',
    nom: 'Préfecture - Vosges',
    abreviation: 'Préfecture - Vosges',
    url: 'http://www.vosges.gouv.fr',
    email: 'prefecture@vosges.gouv.fr',
    telephone: '03 29 69 88 88',
    adresse1: '1, place Foch',
    codePostal: '88026',
    commune: 'Epinal Cedex',
    cedex: 'Cedex',
    departementId: '88'
  },
  'pre-89024-01': {
    id: 'pre-89024-01',
    typeId: 'pre',
    nom: 'Préfecture - Yonne',
    abreviation: 'Préfecture - Yonne',
    url: 'http://www.yonne.gouv.fr',
    email: 'prefecture@yonne.gouv.fr',
    telephone: '03 86 72 79 89',
    adresse1: 'Place de la Préfecture',
    codePostal: '89016',
    commune: 'Auxerre Cedex',
    cedex: 'Cedex',
    departementId: '89'
  },
  'pre-90010-01': {
    id: 'pre-90010-01',
    typeId: 'pre',
    nom: 'Préfecture - Territoire de Belfort',
    abreviation: 'Préfecture - Territoire de Belfort',
    url: 'http://www.territoire-belfort.gouv.fr',
    email: 'courrier90@territoire-de-belfort.pref.gouv.fr',
    telephone: '03 84 57 00 07',
    adresse1: 'Place de la République',
    codePostal: '90020',
    commune: 'Belfort Cedex',
    cedex: 'Cedex',
    departementId: '90'
  },
  'pre-91228-01': {
    id: 'pre-91228-01',
    typeId: 'pre',
    nom: 'Préfecture - Essonne',
    abreviation: 'Préfecture - Essonne',
    url: 'http://www.essonne.gouv.fr',
    email: 'prefecture@essonne.gouv.fr',
    telephone: '01 69 91 91 91',
    adresse1: 'Boulevard de France',
    codePostal: '91010',
    commune: 'Évry Courcouronnes cedex',
    departementId: '91'
  },
  'pre-92050-01': {
    id: 'pre-92050-01',
    typeId: 'pre',
    nom: 'Préfecture - Hauts-de-Seine',
    abreviation: 'Préfecture - Hauts-de-Seine',
    url: 'http://www.hauts-de-seine.gouv.fr',
    email: 'prefecture@hauts-de-seine.gouv.fr',
    telephone: '01 40 97 20 00',
    adresse1: '167-177, avenue Joliot-Curie',
    codePostal: '92013',
    commune: 'Nanterre Cedex',
    departementId: '92'
  },
  'pre-93008-01': {
    id: 'pre-93008-01',
    typeId: 'pre',
    nom: 'Préfecture - Seine-Saint-Denis',
    abreviation: 'Préfecture - Seine-Saint-Denis',
    url: 'http://www.seine-saint-denis.gouv.fr',
    email: 'prefecture@seine-saint-denis.gouv.fr',
    telephone: '01 41 60 60 60',
    adresse1: '1, esplanade Jean-Moulin',
    codePostal: '93007',
    commune: 'Bobigny Cedex',
    cedex: 'Cedex',
    departementId: '93'
  },
  'pre-94028-01': {
    id: 'pre-94028-01',
    typeId: 'pre',
    nom: 'Préfecture - Val-de-Marne',
    abreviation: 'Préfecture - Val-de-Marne',
    url: 'http://www.val-de-marne.gouv.fr',
    email: 'prefecture@val-de-marne.gouv.fr',
    telephone: '01 49 56 60 00',
    adresse1: '21-29, avenue du Général-de-Gaulle',
    codePostal: '94038',
    commune: 'Créteil Cedex',
    cedex: 'Cedex',
    departementId: '94'
  },
  'pre-95127-01': {
    id: 'pre-95127-01',
    typeId: 'pre',
    nom: "Préfecture - Val-d'Oise",
    abreviation: "Préfecture - Val-d'Oise",
    url: 'http://www.val-doise.gouv.fr',
    email: 'prefecture@val-doise.gouv.fr',
    telephone: '01 34 20 95 95',
    adresse1: 'CS 20105, 5, avenue Bernard-Hirsch',
    codePostal: '95010',
    commune: 'Cergy-Pontoise Cedex',
    cedex: 'Cedex',
    departementId: '95'
  },
  'pre-97105-01': {
    id: 'pre-97105-01',
    typeId: 'pre',
    nom: 'Préfecture - Guadeloupe',
    abreviation: 'Préfecture - Guadeloupe',
    url: 'http://www.guadeloupe.pref.gouv.fr',
    telephone: '+590 590 99 39 00',
    adresse1: 'Avenue Paul-Lacavé',
    codePostal: '97109',
    commune: 'Basse-Terre Cedex',
    departementId: '971'
  },
  'pre-97209-01': {
    id: 'pre-97209-01',
    typeId: 'pre',
    nom: 'Préfecture - Martinique',
    abreviation: 'Préfecture - Martinique',
    url: 'http://www.martinique.pref.gouv.fr',
    email: 'contact.prefecture@martinique.pref.gouv.fr',
    telephone: '+596 596 39 36 00',
    adresse1: '82, rue Victor-Sévère',
    codePostal: '97262',
    commune: 'Fort-de-France Cedex',
    departementId: '972'
  },
  'pre-97302-01': {
    id: 'pre-97302-01',
    typeId: 'pre',
    nom: 'Préfecture - Guyane',
    abreviation: 'Préfecture - Guyane',
    url: 'http://www.guyane.pref.gouv.fr',
    email: 'courrier@guyane.pref.gouv.fr',
    telephone: '+594 594 39 45 00',
    adresse1: 'BP 7008, Rue Fiedmond',
    codePostal: '97307',
    commune: 'Cayenne Cedex',
    departementId: '973'
  },
  'pre-97411-01': {
    id: 'pre-97411-01',
    typeId: 'pre',
    nom: 'Préfecture - La Réunion',
    abreviation: 'Préfecture - Réunion',
    url: 'http://www.reunion.gouv.fr',
    telephone: '+262 262 40 77 77',
    adresse1: '1, rue de la Messagerie, CS 51079',
    codePostal: '97404',
    commune: 'Saint-Denis Cedex',
    cedex: 'Cedex',
    departementId: '974'
  },
  'pre-97611-01': {
    id: 'pre-97611-01',
    typeId: 'pre',
    nom: 'Préfecture - Mayotte',
    abreviation: 'Préfecture - Mayotte',
    url: 'http://www.mayotte.pref.gouv.fr/',
    telephone: '+262 269 63 50 00',
    adresse1: 'BP 676, Kawéni, Avenue de la Préfecture',
    codePostal: '97600',
    commune: 'Mamoudzou',
    departementId: '976'
  }
}

export const sortedAdministrations = Object.values(Administrations).sort(
  (a, b) => a.abreviation.localeCompare(b.abreviation)
)
