export const HTTP_STATUS = {
  // OK
  HTTP_STATUS_OK: 200,
  HTTP_STATUS_NO_CONTENT: 204,

  HTTP_STATUS_FOUND: 302,

  HTTP_STATUS_BAD_REQUEST: 400,
  HTTP_STATUS_UNAUTHORIZED: 401,
  HTTP_STATUS_FORBIDDEN: 403,
  HTTP_STATUS_NOT_FOUND: 404,

  HTTP_STATUS_INTERNAL_SERVER_ERROR: 500,
}
