name: api/ci
on:
  push:
    branches-ignore:
      - release-candidate
concurrency:
  group: api-ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '17.8'
          cache: 'npm'
      - name: Npm install
        run: |
          npm set-script prepare ""
          npm ci
        env:
          CI: true
      - name: Lint
        run: npm run ci:lint --workspace=packages/api
      - name: Unit tests
        run: npm run ci:test-unit --workspace=packages/api
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: api-unit, api
  integration-test:
      runs-on: ubuntu-latest
      services:
        postgres:
          image: postgis/postgis:12-3.2
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: camino_tests
            PGUSER: postgres
            PGPASSWORD: password
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            # Maps tcp port 5432 on service container to the host
            - 5432:5432
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '17.8'
            cache: 'npm'
        - name: Npm install
          run: |
            npm set-script prepare ""
            npm ci
          env:
            CI: true
        - name: Integration tests
          run: npm run ci:test-integration --workspace=packages/api
          env:
            PGHOST: localhost
            PGPORT: 5432
            PGUSER: postgres
            PGPASSWORD: password
        - uses: codecov/codecov-action@v2
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            flags: api-integration, api

  build:
    needs: [unit-test, integration-test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t caminofr/camino-api:${GITHUB_SHA} -f Dockerfile.api .
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push Docker image to the Docker Hub
        if: github.ref == 'refs/heads/master'
        run: docker push caminofr/camino-api:${GITHUB_SHA}


