name: api/ci
on:
  push:
concurrency:
  group: api-ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:12-3.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: camino_tests
          PGUSER: postgres
          PGPASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.12'
          cache: 'npm'
      - name: Npm install
        run: |
          npm set-script prepare ""
          npm ci
          npm run ci:lint --workspace=packages/api
          npm run build --workspace=packages/api
        env:
          CI: true
      - name: Unit tests
        run: npm run ci:test-unit --workspace=packages/api
        env:
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: password
      - name: Code coverage
        run: npm run ci:codecov --workspace=packages/api
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Integration tests
        #Installation d’une version de knex-db-manager qui seed la bdd séquentiellement
        run: npm run ci:test-integration --workspace=packages/api
        env:
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: password

  build:
    if: github.ref == 'refs/heads/develop'
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build Docker image
        run: docker build -t caminofr/camino-api:develop packages/api
      - name: Push Docker image to the Docker Hub
        run: |
          docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
          docker push caminofr/camino-api:develop
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
