name: CD
on:
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: 'Environnement de déploiement'     
        required: true
        default: 'dev'
        type: choice
        options: 
        - dev
        - preprod
        - prod
      git_sha:
        description: 'Sha git à déployer'  
        type: string   
        required: true
  workflow_run:
    workflows: ["CI", "Release"]
    branches: [master, release-candidate]
    types: [completed]
env:
  CD_TOKEN_DEV: ${{ secrets.CD_TOKEN_DEV }}
  CD_TOKEN_PREPROD: ${{ secrets.CD_TOKEN_PREPROD }}
  CD_TOKEN_PROD: ${{ secrets.CD_TOKEN_PROD }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Déploiement
        run: INPUT_ENV=${{inputs.deploy_environment}} INPUT_SHA=${{inputs.git_sha}} make deploy/ci
      - name: always
        run: echo "plop $(env)"
