name: CD
on:
  workflow_call:
    inputs:
      # Ne peut être que dev, preprod ou prod
      deploy_environment:
        required: true
        type: string
      git_sha:
        required: true
        type: string
    secrets:
      CD_TOKEN_DEV:
        description: 'le token pour déployer en dev'
        required: true
      CD_TOKEN_PREPROD:
        description: 'le token pour déployer en preprod'
        required: true
      CD_TOKEN_PROD:
        description: 'le token pour déployer en prod'
        required: true
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: 'Environnement de déploiement'     
        required: true
        default: 'dev'
        type: choice
        options: 
        - dev
        - preprod
        - prod
      git_sha:
        description: 'Sha git à déployer'  
        type: string   
        required: true
env:
  CD_TOKEN_DEV: ${{ secrets.CD_TOKEN_DEV }}
  CD_TOKEN_PREPROD: ${{ secrets.CD_TOKEN_PREPROD }}
  CD_TOKEN_PROD: ${{ secrets.CD_TOKEN_PROD }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Déploiement
        run: INPUT_ENV=${{inputs.deploy_environment}} INPUT_SHA=${{inputs.git_sha}} make deploy/ci
