name: CI
on:
  push:
    branches-ignore:
      - preprod
      - prod
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
jobs:
  deadcode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.9'
          cache: 'npm'
      - name: Install
        run:  make install
      - name: Lint
        run: make lint/detect-dead-code
  ui:
    uses: ./.github/workflows/ui.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  api:
    uses: ./.github/workflows/api.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  common:
    uses: ./.github/workflows/common.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  graphql:
    uses: ./.github/workflows/graphql.yml
  doc:
    uses: ./.github/workflows/doc.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  openfisca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build . --build-arg GIT_SHA=${GITHUB_SHA} -f Dockerfile.openfisca -t caminofr/camino-openfisca:${GITHUB_SHA}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push Docker image to the Docker Hub
        if: github.ref == 'refs/heads/master'
        run: docker push caminofr/camino-openfisca:${GITHUB_SHA}
  deploy:
    needs: [ui, api, common, doc, openfisca, graphql]
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/cd.yml
    secrets:
      CD_TOKEN_DEV: ${{ secrets.CD_TOKEN_DEV }}
      CD_TOKEN_PREPROD: ${{ secrets.CD_TOKEN_PREPROD }}
      CD_TOKEN_PROD: ${{ secrets.CD_TOKEN_PROD }}
    with:
      deploy_environment: dev
      git_sha: ${{ github.sha }}
