name: CI
on:
  push:
    branches-ignore:
      - preprod
      - prod
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
jobs:
  ui:
    uses: ./.github/workflows/ui.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  api:
    uses: ./.github/workflows/api.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  common:
    uses: ./.github/workflows/common.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  graphql:
    uses: ./.github/workflows/graphql.yml
  doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Generate docs
        run: make docs/build
      - name: Build Docker image
        run: docker build -f Dockerfile.api.docs -t caminofr/camino-api-docs:${GITHUB_SHA} .
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push Docker image to the Docker Hub
        if: github.ref == 'refs/heads/feat-map-libre'
        run: docker push caminofr/camino-api-docs:${GITHUB_SHA}
  openfisca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build . --build-arg GIT_SHA=${GITHUB_SHA} -f Dockerfile.openfisca -t caminofr/camino-openfisca:${GITHUB_SHA}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push Docker image to the Docker Hub
        if: github.ref == 'refs/heads/feat-map-libre'
        run: docker push caminofr/camino-openfisca:${GITHUB_SHA}
  deploy:
    needs: [ui, api, common, doc, openfisca, graphql]
    if: github.ref == 'refs/heads/feat-map-libre'
    uses: ./.github/workflows/cd.yml
    secrets:
      CD_TOKEN_DEV: ${{ secrets.CD_TOKEN_DEV }}
      CD_TOKEN_PREPROD: ${{ secrets.CD_TOKEN_PREPROD }}
      CD_TOKEN_PROD: ${{ secrets.CD_TOKEN_PROD }}
    with:
      deploy_environment: dev
      git_sha: ${{ github.sha }}
