name: Deploy
on:
  push:
    branches:
      - prod
      - preprod
jobs:
  release-github:
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.1'
          cache: 'npm'
      - name: Install
        run: make install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MATTERMOST_WEBHOOK: ${{ secrets.MATTERMOST_WEBHOOK }}
        run: npx semantic-release
  deploy-prod:
    if: github.ref == 'refs/heads/prod'
    needs: release-github
    uses: ./.github/workflows/cd.yml
    secrets:
      CD_TOKEN_DEV: ${{ secrets.CD_TOKEN_DEV }}
      CD_TOKEN_PREPROD: ${{ secrets.CD_TOKEN_PREPROD }}
      CD_TOKEN_PROD: ${{ secrets.CD_TOKEN_PROD }}
    with:
      deploy_environment: prod
      git_sha: ${{ github.sha }}
  deploy-preprod:
    if: github.ref == 'refs/heads/preprod'
    uses: ./.github/workflows/cd.yml
    secrets:
      CD_TOKEN_DEV: ${{ secrets.CD_TOKEN_DEV }}
      CD_TOKEN_PREPROD: ${{ secrets.CD_TOKEN_PREPROD }}
      CD_TOKEN_PROD: ${{ secrets.CD_TOKEN_PROD }}
    with:
      deploy_environment: preprod
      git_sha: ${{ github.sha }}
