name: Documentation
on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        description: 'le user docker'
        required: true
      DOCKER_TOKEN:
        description: 'le token docker'
        required: true
jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -f Dockerfile.docs -t caminofr/camino-docs:${GITHUB_SHA} .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push Docker image to the Docker Hub
        if: github.ref == 'refs/heads/master'
        run: docker push caminofr/camino-docs:${GITHUB_SHA}
