name: Release
on:
  push:
    branches:
      - release-candidate
jobs:
  release-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.1'
          cache: 'npm'
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
  deploy:
    needs: release-github
    uses: ./.github/workflows/cd.yml
    secrets:
      CD_TOKEN_DEV: ${{ secrets.CD_TOKEN_DEV }}
      CD_TOKEN_PREPROD: ${{ secrets.CD_TOKEN_PREPROD }}
      CD_TOKEN_PROD: ${{ secrets.CD_TOKEN_PROD }}
    with:
      deploy_environment: prod
      git_sha: ${{ github.sha }}
