name: ui/ci
on:
  push:
concurrency:
  group: ui-ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.12'
          cache: 'npm'
      - name: Test units
        run: |
          npm set-script prepare ""
          npm ci
          npm run build --workspace=packages/ui
          npm test --workspace=packages/ui
        env:
          CODECOV_TOKEN:  ${{ secrets.CODECOV_TOKEN }}
          CI: true

  build:
    if: github.ref == 'refs/heads/develop'
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build Docker image
        run: docker build . -f Dockerfile.ui --tag caminofr/camino-ui:develop
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push Docker image to the Docker Hub
        run: docker push caminofr/camino-ui:develop

