name: ui/ci
on:
  push:
concurrency:
  group: ui-ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '17.8'
          cache: 'npm'
      - name: Test units
        run: |
          npm set-script prepare ""
          npm ci
          npm run lint:check --workspace=packages/ui
          npm test --workspace=packages/ui
          npm run codecov --workspace=packages/ui
        env:
          CODECOV_TOKEN:  ${{ secrets.CODECOV_TOKEN }}
          CI: true

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build . --build-arg GIT_SHA=${GITHUB_SHA} -f Dockerfile.ui -t caminofr/camino-ui:${GITHUB_SHA}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push Docker image to the Docker Hub
        if: github.ref == 'refs/heads/master'
        run: docker push caminofr/camino-ui:${GITHUB_SHA}

